### ISSUE TITLE
Version 1.2.0 encounters an error when using the -f parameter

### ISSUE THREAD

**Issue by Mgrsc** [containers/podman-compose#1059]
**Describe the bug**
In version 1.2.0, I encountered an error while using 'podman-compose -f lobe/compose.yaml pull', but it worked fine in version 1.1.0. Using the absolute path works normally, but using the relative path results in an error.

```shell
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/podman_compose.py", line 3526, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/podman_compose.py", line 3522, in async_main
    await podman_compose.run()
  File "/usr/local/lib/python3.11/dist-packages/podman_compose.py", line 1753, in run
    self._parse_compose_file()
  File "/usr/local/lib/python3.11/dist-packages/podman_compose.py", line 1848, in _parse_compose_file
    with open(filename, "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'lobe/compose.yaml'
```

**To Reproduce**
1. There is a compose.yaml file for lobe-chat in the lobe directory.
2. Go back to the parent directory and run: podman-compose -f lobe/compose.yaml pull.

**Expected behavior**
nomal pull

**Actual behavior**
What is the behavior you actually got and that should not happen.

**Output**

```
$ podman-compose version
podman-compose version 1.2.0
podman version 5.2.2


$ podman-compose -f lobe/compose.yaml pull
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/podman_compose.py", line 3526, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/podman_compose.py", line 3522, in async_main
    await podman_compose.run()
  File "/usr/local/lib/python3.11/dist-packages/podman_compose.py", line 1753, in run
    self._parse_compose_file()
  File "/usr/local/lib/python3.11/dist-packages/podman_compose.py", line 1848, in _parse_compose_file
    with open(filename, "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'lobe/compose.yaml'


**Environment:**
 - OS: Linux
 - podman version:  5.2.2
 - podman compose version: 1.2.0

**Comment by UgnilJoZ** [comment]
Seems like the relative path is used after the working directory is changed. Interestingly, there is a "TODO Remove" comment above the directory change in [line 1815](https://github.com/containers/podman-compose/blob/main/podman_compose.py#L1815).

**Comment by midlan** [comment]
run into same bug today

steps to reproduce:
```
echo -e "services:\n  a:\n    image: hello-world" > c.yml
podman-compose -f c.yml up #works
mkdir subdir
mv c.yml subdir/
podman-compose -f subdir/c.yml up #fails
```

removing https://github.com/containers/podman-compose/blob/main/podman_compose.py#L1818 fixes the issue

**Comment by midlan** [comment]
I can confirm that with `v1.1.0` it works, and the line is present there
https://github.com/containers/podman-compose/blob/v1.1.0/podman_compose.py#L1685

so it seems to be introduced by something else between `v1.1.0` and `v1.2.0`

**Comment by jonwiggins** [comment]
Looks like the old versions have been removed from brew.

I was able to install version 1.1.0 with: 
```
brew uninstall podman-compose
rm '/opt/homebrew/bin/podman-compose'
curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/07d7ff2920c03efa1765d856d66dc71e66d95b5b/Formula/p/podman-compose.rb
HOMEBREW_NO_AUTO_UPDATE=1 brew install -s podman-compose.rb
brew link podman-compose
```
This works until a fix is released.

**Comment by starnight** [comment]
This issue can be reproduced in `v1.3.0`, too.

**Comment by cfunkhouser** [comment]
#1124 fixed the similar issue #1109, and appears to have also fixed this issue. Can anyone else verify?

**Comment by starnight** [comment]
> [#1124](https://github.com/containers/podman-compose/pull/1124) fixed the similar issue [#1109](https://github.com/containers/podman-compose/issues/1109), and appears to have also fixed this issue. Can anyone else verify?

#1124 fixes this issue on my site.  Thanks!
