### ISSUE TITLE
Podman Compose failing on Archivebox docker-compose.yml

### ISSUE THREAD

**Issue by parkerlreed** [containers/podman-compose#1065]
**Describe the bug**
I am able to run the init command from here https://github.com/ArchiveBox/ArchiveBox?tab=readme-ov-file#%EF%B8%8F-easy-setup

But upon trying to start the container with `compose up` I get an error about the docker file not being found.

**To Reproduce**
1. Contents of folder in output below
2. Downloaded their docker-compose-yml, ran the init command `docker compose run archivebox init --setup`, and then tried running `compose up`

**Expected behavior**
Container to start

**Actual behavior**
Fails to find docker file

**Output**

```
[parker@thinknas archivebox]$ ls -lah
total 24K
drwxr-xr-x  3 parker parker 4.0K Nov  1 13:47 .
drwx------ 17 parker parker 4.0K Nov  1 13:36 ..
drwxr-xr-x  5 100910 100910 4.0K Nov  1 13:54 data
-rw-r--r--  1 parker parker 9.8K Nov  1 13:47 docker-compose.yml
[parker@thinknas archivebox]$ podman-compose version
podman-compose version 1.2.0
podman version 5.2.5
[parker@thinknas archivebox]$ podman-compose up
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.2.0', 'console_scripts', 'podman-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/podman_compose.py", line 3550, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/podman_compose.py", line 3546, in async_main
    await podman_compose.run()
  File "/usr/lib/python3.12/site-packages/podman_compose.py", line 1775, in run
    retcode = await cmd(self, args)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/podman_compose.py", line 2511, in compose_up
    if await compose.commands["build"](compose, build_args) != 0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/podman_compose.py", line 2461, in compose_build
    s = await t
        ^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 631, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/podman_compose.py", line 2407, in build_one
    raise OSError("Dockerfile not found in " + ctx)
OSError: Dockerfile not found in /home/parker/.local/share/archivebox
```

**Environment:**
 - OS: Arch Linux
 - podman version: 5.2.5
 - podman compose version: 1.2.0/master

**Comment by parkerlreed** [comment]
Is it maybe the dockerfile_inline for `sonic` causing this?

**Comment by parkerlreed** [comment]
I removed sonic as it is optional and it seems to be starting

**Comment by pirate** [comment]
It's this issue: https://github.com/containers/podman-compose/issues/864
