### ISSUE TITLE
Failure when trying to start a docker-hadoop cluster

### ISSUE THREAD

**Issue by AntonOellerer** [containers/podman-compose#131]
Hey, 
I am trying to create a hadoop cluster with podman, and for this cloned the [docker-hadoop](https://github.com/big-data-europe/docker-hadoop) repository and ran `podman-compose up`.
Starting of the NameNode fails with the following error:
```Java
java.io.IOException: java.lang.RuntimeException: Could not resolve Kerberos principal name: java.net.UnknownHostException: 2027a5c01347: 2027a5c01347: Name or service not known
        at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:553) 
        at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:119)
        at org.apache.hadoop.http.HttpServer2$Builder.build(HttpServer2.java:433) 
        at org.apache.hadoop.hdfs.server.namenode.NameNodeHttpServer.start(NameNodeHttpServer.java:164)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.startHttpServer(NameNode.java:885)                    
        at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:707)                                                                                                                                                      
        at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:953)         
        at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:926)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1692)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1759)
Caused by: java.lang.RuntimeException: Could not resolve Kerberos principal name: java.net.UnknownHostException: 2027a5c01347: 2027a5c01347: Name or service not known
        at org.apache.hadoop.security.AuthenticationFilterInitializer.getFilterConfigMap(AuthenticationFilterInitializer.java:86)
        at org.apache.hadoop.http.HttpServer2.getFilterProperties(HttpServer2.java:665)
        at org.apache.hadoop.http.HttpServer2.constructSecretProvider(HttpServer2.java:655)
        at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:546)
        ... 9 more                                                                                                     
Caused by: java.net.UnknownHostException: 2027a5c01347: 2027a5c01347: Name or service not known
        at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
        at org.apache.hadoop.security.SecurityUtil.getLocalHostName(SecurityUtil.java:259)
        at org.apache.hadoop.security.SecurityUtil.replacePattern(SecurityUtil.java:227)
        at org.apache.hadoop.security.SecurityUtil.getServerPrincipal(SecurityUtil.java:182)
        at org.apache.hadoop.security.AuthenticationFilterInitializer.getFilterConfigMap(AuthenticationFilterInitializer.java:83)
        ... 12 more
Caused by: java.net.UnknownHostException: 2027a5c01347: Name or service not known
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
        ... 16 more

```
Because of this, the whole cluster is unable to start.
I am using the latest development version as advised in the README on Fedora 31
`podman-compose version`:
```
podman-composer version  0.1.6dev
podman --version
podman version 1.8.1
0
```

**Comment by NewestUser** [comment]
I have a similar problem when trying to run a java app inside a docker container which I start with podman-compose.

It seems that this is the line of code that causes the issue to appear
```java
java.net.InetAddress.getLocalHost().getHostName()
```

The exception is:
```java
Caused by: java.net.UnknownHostException: ec3086cec320: Name or service not known
```

I do not observe such an error when ruining the container with a regular docker-compose command.

My docker-compose.yml is :
```yml
version: '3.7'

networks:
  my-network:
    driver: bridge

...

java-backend:
    image: java-backend:app
    networks:
      - my-network
    depends_on:
      - mysql
      - redis
      - zookeeper
      - kafka
      - elastic
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
```

I am using a development version as advised in the README on CentOS Linux 8 (Core)

`podman-compose version`:

```text
using podman version: podman version 1.6.4
podman-composer version  0.1.7dev
podman --version
podman version 1.6.4
0
```

**Comment by NewestUser** [comment]
I noticed that when running a container with docker-compose the `hostname` of the container is added in `/etc/hosts`
Example:
```shell script
root@bb7563cc0b43:/# hostname 
bb7563cc0b43

root@bb7563cc0b43:/# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.19.0.7	bb7563cc0b43
```

While using podman-compose the hostname was missing in the containers `/etc/hosts`

**Comment by mokibit** [comment]
I can no longer reproduce this issue with the following configuration:
Environment:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```

Verification steps
`docker-compose.yml`:
```
services:
  testhost:
    image: docker.io/library/alpine:latest
    command: ["sleep", "3600"]
```
Start the container:
```
$ podman-compose up -d
```

Check that the hostname resolves (this is what `java.net.InetAddress.getLocalHost()` does internally):
1. Show the container's hostname (the container has a hostname assigned by podman)
```
$ podman-compose exec testhost sh -c 'hostname'
1508db654342
```
 2. Verify the hostname is resolvable via DNS/nsswitch.
The hostname successfully resolves to the container's IP address. With older versions of Podman, this would fail with: "Name or service not known"
```
$ podman-compose exec testhost sh -c 'getent hosts $(hostname)'
10.89.26.2        1508db654342  1508db654342
```
 3. Inspect `/etc/hosts` to see the actual entry added by Podman.
```
$ podman-compose exec testhost sh -c 'cat /etc/hosts'
127.0.0.1       localhost
[...]
::1     localhost ip6-localhost ip6-loopback
[...]
169.254.1.2     host.containers.internal host.docker.internal
10.89.26.2      1508db654342 test-podman-compose_testhost_1
```
With modern Podman, the hostname is automatically injected and resolves correctly, so Java applications (and any other code relying on `gethostbyname(hostname)`) now work.

If you still experience this on a current `podman-compose` version, please reopen with updated environment details.
