### ISSUE TITLE
Podman compose should give nicer error if podman is not installed

### ISSUE THREAD

**Issue by harsh183** [containers/podman-compose#152]
When I tried it gave me 
```
podman pod create --name=killbill --share net -p 8080:8080 -p 9090:8080
Traceback (most recent call last):
  File "/home/harsh183/.local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/home/harsh183/.local/lib/python3.6/site-packages/podman_compose.py", line 1093, in main
    podman_compose.run()
  File "/home/harsh183/.local/lib/python3.6/site-packages/podman_compose.py", line 625, in run
    cmd(self, args)
  File "/home/harsh183/.local/lib/python3.6/site-packages/podman_compose.py", line 782, in wrapped
    return func(*args, **kw)
  File "/home/harsh183/.local/lib/python3.6/site-packages/podman_compose.py", line 895, in compose_up
    create_pods(compose, args)
  File "/home/harsh183/.local/lib/python3.6/site-packages/podman_compose.py", line 862, in create_pods
    compose.podman.run(podman_args)
  File "/home/harsh183/.local/lib/python3.6/site-packages/podman_compose.py", line 590, in run
    p = subprocess.Popen(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'podman': 'podman'
```

**Comment by harsh183** [comment]
Brilliant! Thanks
