### ISSUE TITLE
AttributeError on the latest devel

### ISSUE THREAD

**Issue by goncalossilva** [containers/podman-compose#161]
Using the latest `devel`, podman-compose fails early:

```
Traceback (most recent call last):
  File "/home/goncalossilva/.conda/envs/podman-compose/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/home/goncalossilva/.conda/envs/podman-compose/lib/python3.7/site-packages/podman_compose.py", line 1374, in main
    podman_compose.run()
  File "/home/goncalossilva/.conda/envs/podman-compose/lib/python3.7/site-packages/podman_compose.py", line 820, in run
    cmd(self, args)
  File "/home/goncalossilva/.conda/envs/podman-compose/lib/python3.7/site-packages/podman_compose.py", line 1008, in wrapped
    return func(*args, **kw)
  File "/home/goncalossilva/.conda/envs/podman-compose/lib/python3.7/site-packages/podman_compose.py", line 1117, in compose_up
    compose.commands['build'](compose, build_args)
  File "/home/goncalossilva/.conda/envs/podman-compose/lib/python3.7/site-packages/podman_compose.py", line 1008, in wrapped
    return func(*args, **kw)
  File "/home/goncalossilva/.conda/envs/podman-compose/lib/python3.7/site-packages/podman_compose.py", line 1084, in compose_build
    build_one(compose, args, cnt)
  File "/home/goncalossilva/.conda/envs/podman-compose/lib/python3.7/site-packages/podman_compose.py", line 1076, in build_one
    for build_arg in args_list + args.build_arg:
AttributeError: 'Namespace' object has no attribute 'build_arg'
```

Python 3.7.7, same result on Python 3.8.2.

**Comment by s0h3ck** [comment]
I can reproduce it. @jerdna-regeiz [[author](https://github.com/containers/podman-compose/commit/19733407b46dc23209ddda2cabd48fab77332228)] can you comment on this?

Is it suppose to be `for build_arg in args_list + build_args`?

**Comment by jerdna-regeiz** [comment]
> I can reproduce it. @jerdna-regeiz [[author](https://github.com/containers/podman-compose/commit/19733407b46dc23209ddda2cabd48fab77332228)] can you comment on this?
> 
> Is it suppose to be `for build_arg in args_list + build_args`?

Nope, it should not. `args.build_arg` is correct as this is how [argparse](https://docs.python.org/3/library/argparse.html) handles `action="append"`.
~I can not reproduce it (fresh Ubuntu 20.04 Python 3.8.2).~

Just reproduced it while typing. It happens when build is called from up.
I'll fix it as soon as possible. In the meantime, just do a podman-compose build first.
Sorry for the inconvenience.
