### ISSUE TITLE
Build with Containerfile instead of Dockerfile

### ISSUE THREAD

**Issue by dduenker** [containers/podman-compose#167]
I just tried to create a stack which uses a file named `Containerfile` instead of `Dockerfile`, which apparently does not work.
Is it possible to support the tool agnostic `Containerfile` as filename?

On a related note: why not use `container-compose.yaml` as well? :)

**Comment by smarnv** [comment]
I would also appreciate support for `Containerfile`. Using `container-compose.y(a)ml` is already possible (see #46).

**Comment by delight-aug** [comment]
It's strange it isn't a thing yet. I say it has to be of a higher priority since Podman itself uses "Containerfile" just fine

**Comment by muayyad-alsadi** [comment]
please test

**Comment by delight-aug** [comment]
```
❯ podman-compose up
Error: error inspecting object: bib_db: image not known
Traceback (most recent call last):
  File "/home/mks/.local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/home/mks/.local/lib/python3.10/site-packages/podman_compose.py", line 1093, in main
    podman_compose.run()
  File "/home/mks/.local/lib/python3.10/site-packages/podman_compose.py", line 625, in run
    cmd(self, args)
  File "/home/mks/.local/lib/python3.10/site-packages/podman_compose.py", line 782, in wrapped
    return func(*args, **kw)
  File "/home/mks/.local/lib/python3.10/site-packages/podman_compose.py", line 884, in compose_up
    compose.commands['build'](compose, build_args)
  File "/home/mks/.local/lib/python3.10/site-packages/podman_compose.py", line 782, in wrapped
    return func(*args, **kw)
  File "/home/mks/.local/lib/python3.10/site-packages/podman_compose.py", line 850, in compose_build
    build_one(compose, args, cnt)
  File "/home/mks/.local/lib/python3.10/site-packages/podman_compose.py", line 834, in build_one
    raise OSError("Dockerfile not found in "+ctx)
OSError: Dockerfile not found in db/.
```
Writing `build: db/Containerfile` in the docker-compose.yml didn't help.
Here is Containerfile at `db/Containerfile`:
```
FROM mongo:latest
COPY init.js /docker-entrypoint-initdb.d/init.db
```
It worked perfectly fine with [docker-compose wired to podman](https://fedoramagazine.org/use-docker-compose-with-podman-to-orchestrate-containers-on-fedora/)

docker-compose.yml:
```
version: "3.9"

services:
  db:
    build: db/.
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${MONGO_DB_DIR}:/data/db
    networks:
      - backend

  api:
    build: api/.
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
```

**Comment by muayyad-alsadi** [comment]
```
File "/home/mks/.local/lib/python3.10/site-packages/podman_compose.py", line 834, in build_one
    raise OSError("Dockerfile not found in "+ctx)
OSError: Dockerfile not found in db/.
```

this does not seem to be my code, the raise statement in my code is around line 1343

**Comment by delight-aug** [comment]
Oh, turns out this is because pip features an old release. See #338

**Comment by muayyad-alsadi** [comment]
Would you please confirm if the latest devel branch fix it?

**Comment by delight-aug** [comment]
Hi, sorry it took so long. The devel version works just fine. Thanks.
