### ISSUE TITLE
Gives a confusing message for empty compose file

### ISSUE THREAD

**Issue by samtygier** [containers/podman-compose#169]
If the compose file is empty podman-compose gives the error:

```
$ podman-compose up
Traceback (most recent call last):
  File "bin/podman-compose", line 11, in <module>
    load_entry_point('podman-compose', 'console_scripts', 'podman-compose')()
  File "podman-compose/podman_compose.py", line 1374, in main
    podman_compose.run()
  File "podman-compose/podman_compose.py", line 797, in run
    self._parse_compose_file()
  File "podman-compose/podman_compose.py", line 877, in _parse_compose_file
    content = normalize(content)
  File "podman-compose/podman_compose.py", line 719, in normalize
    services = compose.get("services", None) or {}
AttributeError: 'NoneType' object has no attribute 'get'

```
This is because `yaml.safe_load(f)` will return `None`.

In comparison docker-compose gives:
```
ERROR: Top level object in './docker-compose.yaml' needs to be an object not '<class 'NoneType'>'
```

Patch to follow.

**Comment by samtygier** [comment]
Please could I get some feed back as to why this was closed. Thanks.

**Comment by muayyad-alsadi** [comment]
your PR is merged and problem is fixed.

sorry I was using github on my mobile.

**Comment by samtygier** [comment]
Thanks. Mobile interfaces can be a pain :-)
