### ISSUE TITLE
TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by dongbum** [containers/podman-compose#204]
I have installed the latest version of podman-compose. (Using pip3)
When starting with [docker-compose.yml](https://docs.teslamate.org/docs/installation/docker) script, I found the following error:

```
[root@localhost teslamate]# podman-compose -f docker-compose.yml up -d
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/podman_compose.py", line 1093, in main
    podman_compose.run()
  File "/usr/local/lib/python3.8/site-packages/podman_compose.py", line 611, in run
    self._parse_compose_file()
  File "/usr/local/lib/python3.8/site-packages/podman_compose.py", line 666, in _parse_compose_file
    compose['_dirname']=dirname
TypeError: 'NoneType' object does not support item assignment
[root@localhost teslamate]#
```

OS : 'Linux CentOS 8'.
Python : 3.8.0

How can I solve this error messages?

**Comment by muayyad-alsadi** [comment]
It seems that your yaml file did not parse to object but to null/none

It could that you have an empty yaml fole

**Comment by dongbum** [comment]
Thanks. It's my mistake. File is empty. :laughing:

If the file is empty, it would be better stop process and show error message.
