### ISSUE TITLE
docker-compose.yml with empty ports parameters fails

### ISSUE THREAD

**Issue by joequant** [containers/podman-compose#242]
```
version:  '3'
services:
  core-dev:
     image: "joequant/core-dev"
     ports:
     volumes:
       - user:/home/user
       - log:/var/log

volumes:
      user:
      log:
```

fails with 

```
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/podman_compose.py", line 1093, in main
    podman_compose.run()
  File "/usr/local/lib/python3.8/site-packages/podman_compose.py", line 625, in run
    cmd(self, args)
  File "/usr/local/lib/python3.8/site-packages/podman_compose.py", line 782, in wrapped
    return func(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/podman_compose.py", line 897, in compose_up
    podman_args = container_to_args(compose, cnt,
  File "/usr/local/lib/python3.8/site-packages/podman_compose.py", line 465, in container_to_args
    for i in cnt.get('ports', []):
TypeError: 'NoneType' object is not iterable
```

**Comment by stellarpower** [comment]
Same for other keys, and with comments:
```
...
cap_add:
#    - NET_ADMIN
ports:
...
```
I'm guessing most keys should simply be ignorable if there's nothing provided.

**Comment by muayyad-alsadi** [comment]
the code now reads

```
ports = cnt.get('ports', None) or []
```
