### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by jagusztinl** [containers/podman-compose#258]
Tried to set up up the DefectDojo project: https://github.com/DefectDojo/django-DefectDojo/blob/master/DOCKER.md

[root@localhost django-DefectDojo]# podman-compose up
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/podman_compose.py", line 1093, in main
    podman_compose.run()
  File "/usr/local/lib/python3.6/site-packages/podman_compose.py", line 611, in run
    self._parse_compose_file()
  File "/usr/local/lib/python3.6/site-packages/podman_compose.py", line 729, in _parse_compose_file
    project_name, container_names_by_service, given_containers)
  File "/usr/local/lib/python3.6/site-packages/podman_compose.py", line 346, in tr_1podfw
    move_port_fw(pod, containers)
  File "/usr/local/lib/python3.6/site-packages/podman_compose.py", line 250, in move_port_fw
    move_list(dst, containers, "ports")
  File "/usr/local/lib/python3.6/site-packages/podman_compose.py", line 240, in move_list
    a.update(a0)
TypeError: unhashable type: 'dict'

What is the problem? With docker compose works pefectly.

**Comment by argonauts12** [comment]
It looks like podman compose doesn't support the long form ports definition [Port mapping](https://www.dev-diaries.com/social-posts/docker-port-mappings/).
Try modifying it to be the following just to confirm that that is the issue. 

```
 ports:
   - 8080:8080
   - 8443:8443
```

**Comment by mokibit** [comment]
I cannot reproduce this issue anymore.
Environment:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```
`compose.yml` file:
```
services:
  web:
    image: busybox
    ports:
      - target: 8080
        published: 8080
      - target: 8443
        published: 8443

```
Run command:
```
./podman_compose.py --dry-run up
```
It no longer raises the `TypeError: unhashable type: 'dict' error`.
 Older versions of podman-compose did not support the long-form (dict) port mapping syntax defined by the Compose specification, but this has since been fixed.
