### ISSUE TITLE
Unable to use even with basic yml file...

### ISSUE THREAD

**Issue by ardijanr** [containers/podman-compose#266]
Trying to use this, but just getting an error...

using a fresh fedora 33 vm from digitalocean.
```
[podman@fedora-s-2vcpu-2gb-lon1-01 site1]$ podman-compose up
using podman version: podman version 2.2.1
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==0.1.7.dev0', 'console_scripts', 'podman-compose')())
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 1412, in main
    podman_compose.run()
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 824, in run
    self._parse_compose_file()
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 909, in _parse_compose_file
    flat_deps(services, with_extends=True)
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 665, in flat_deps
    srv["_deps"] = deps
TypeError: 'str' object does not support item assignment
```

**Comment by muayyad-alsadi** [comment]
what is your yml?

**Comment by ardijanr** [comment]
yeah, sorry
tried commenting out most of it without luck...
```
version: '3'

services:
  image: alpine:latest
  domainname: site1.com
  hostname: site1
  deploy:
    replicas: 1
    resources:
      limits:
        cpus: '1'
        memory: 512M
  ports:
  - '8080'
  working_dir: /
  volumes:
        - .:/container
  
```

**Comment by muayyad-alsadi** [comment]
your yaml has servcies that is not a key value mapping as it should

https://github.com/compose-spec/compose-spec/blob/master/spec.md#illustrative-example

```yaml
---
services:
  my_srv_name:
    image: something
    # ....
```

in JSON terms 

```javascript
{"services": {"my_srv_name": {"image": /*....*/ }}
```

**Comment by ardijanr** [comment]
ah, thnx new to podman/docker. I'll RTFM next time. However a comfort feature would be a hint to what the mistake was.
