### ISSUE TITLE
Symlinked docker-compose.yml messes up the paths

### ISSUE THREAD

**Issue by jilleJr** [containers/podman-compose#268]
If the docker-compose.yml file is a symlink, then all contexts for the `podman-compose build` command is relative the where the docker-compose.yml file links to, and not from where the link sits.

Maybe this is intentional, but we previously relied on this behaviour when using docker.

For our solution, we use a lot of repos, and then we have one repo which contains the docker-compose.yml file. Just to paint the picture, in our docs we tell our devs to do the following:

```sh
git pull ssh://gitlab/api
git pull ssh://gitlab/web
git pull ssh://gitlab/other-repo1
git pull ssh://gitlab/other-repo2
git pull ssh://gitlab/docs
ln -s docs/docker-compose.yml docker-compose.yml
```

It's very useful, but with podman-compose I have to remove the symlink and copy the file regularly instead.

## Expected behaviour

`podman-compose build` builds with contexts relative to where the docker-compose.yml file sits, no matter if that file is a symlink or not

## Actual behaviour

If the docker-compose.yml file in the folder is a symlink, then all contexts are relative to the original file that the docker-compose.yml link points to.

## Error

```sh
$ podman-compose build
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/podman_compose.py", line 1093, in main
    podman_compose.run()
  File "/usr/local/lib/python3.8/dist-packages/podman_compose.py", line 625, in run
    cmd(self, args)
  File "/usr/local/lib/python3.8/dist-packages/podman_compose.py", line 782, in wrapped
    return func(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/podman_compose.py", line 850, in compose_build
    build_one(compose, args, cnt)
  File "/usr/local/lib/python3.8/dist-packages/podman_compose.py", line 834, in build_one
    raise OSError("Dockerfile not found in "+ctx)
OSError: Dockerfile not found in api
```

## Workaround

```sh
$ rm docker-compose.yml
$ cp docs/docker-compose.yml .
$ podman-compose build
podman build -t project_api -f api/Dockerfile api
STEP 1: FROM redacted AS build
Getting image source signatures
Copying blob 2a19d2e6789c [--------------------------------------] 776.2KiB / 65.3MiB
Copying blob 16ea0e8c8879 [--------------------------------------] 573.2KiB / 48.0MiB
Copying blob bd9cab5aeb31 [--------------------------------------] 651.2KiB / 114.5MiB
Copying blob ff95660c6937 [==>-----------------------------------] 659.3KiB / 9.5MiB
Copying blob 9c7d0e5c0bc2 [>-------------------------------------] 736.3KiB / 49.4MiB
Copying blob 50024b0106d5 [==>-----------------------------------] 596.8KiB / 7.4MiB
```

---

```sh
$ sudo pip3 list | grep podman-compose
podman-compose         0.1.5
$ podman --version
podman version 2.2.1
```

**Comment by jilleJr** [comment]
Oh found #130 now, but not when I searched before creating this issue. Closing this as duplicate
