### ISSUE TITLE
podman-compose tries to inspect a volume before creation

### ISSUE THREAD

**Issue by raveinid** [containers/podman-compose#285]
Shouldn't podman-compose use podman volume exist XXXXXXXX_XXX-caddy-data || podman volume create XXXXXXXX_XXX-caddy-data

podman volume inspect XXXXXXXX_XXX-caddy-data || podman volume create XXXXXXXX_XXX-caddy-data
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/podman_compose.py", line 1093, in main
    podman_compose.run()
  File "/usr/local/lib/python3.8/dist-packages/podman_compose.py", line 625, in run
    cmd(self, args)
  File "/usr/local/lib/python3.8/dist-packages/podman_compose.py", line 782, in wrapped
    return func(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/podman_compose.py", line 897, in compose_up
    podman_args = container_to_args(compose, cnt,
  File "/usr/local/lib/python3.8/dist-packages/podman_compose.py", line 457, in container_to_args
    mount_args = mount_desc_to_args(compose, volume, cnt['_service'], cnt['name'])
  File "/usr/local/lib/python3.8/dist-packages/podman_compose.py", line 386, in mount_desc_to_args
    mount_desc = mount_dict_vol_to_bind(compose, fix_mount_dict(mount_desc, proj_name, srv_name))
  File "/usr/local/lib/python3.8/dist-packages/podman_compose.py", line 366, in mount_dict_vol_to_bind
    src = json.loads(out)[0]["mountPoint"]
KeyError: 'mountPoint'

**Comment by jennydaman** [comment]
Hey, I had this problem too on podman-compose v0.1.5 from pypi.

Installing the development version worked for me

```bash
pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
```
