### ISSUE TITLE
docker compose example doesn't work?

### ISSUE THREAD

**Issue by jfmatth** [containers/podman-compose#329]
Hello, thank you for Podman-compose and Podman, they are much easier to work with than Docker.

However, maybe i'm not doing something right, but on a Fedora 34 install and Podman, and Podman-compose installed, I cannot get the sample docker compose to work https://docs.docker.com/samples/django/

I don't know if it's that Podman-compose does things differently or what.

Here is my output
```
jfmatth@fedora podman-compose]$ podman-compose run web django-admin startproject composeexample .
using podman version: podman version 3.3.0
podman pod create --name=podman-compose --share net -p 8000:8000
Error: error adding pod to state: name "podman-compose" is in use: pod already exists
125
Namespace(file=['docker-compose.yml'], project_name=None, podman_path='podman', no_ansi=False, no_cleanup=False, dry_run=False, transform_policy='1podfw', command='run', detach=False, name=None, entrypoint=None, e=None, label=None, user=None, no_deps=False, rm=False, publish=None, service_ports=False, volume=None, T=False, workdir=None, service='web', cnt_command=['django-admin', 'startproject', 'composeexample', '.'])
podman run -i --name=podman-compose_web_tmp24097 --pod=podman-compose --label io.podman.compose.config-hash=123 --label io.podman.compose.project=podman-compose --label io.podman.compose.version=0.0.1 --label com.docker.compose.container-number=1 --label com.docker.compose.service=web -v /home/jfmatth/development/podman-compose/.:/code --add-host db:127.0.0.1 --add-host podman-compose_db_1:127.0.0.1 --add-host web:127.0.0.1 --add-host podman-compose_web_1:127.0.0.1 --tty podman-compose_web django-admin startproject composeexample .
Traceback (most recent call last):
  File "/usr/local/bin/django-admin", line 8, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/startproject.py", line 21, in handle
    super().handle('project', project_name, target, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/templates.py", line 160, in handle
    with open(new_path, 'w', encoding='utf-8') as new_file:
PermissionError: [Errno 13] Permission denied: '/code/manage.py'

```

**Comment by muayyad-alsadi** [comment]
are you using the devel branch?

**Comment by jfmatth** [comment]
did just a regular DNF install version

```
[jfmatth@fedora ~]$ dnf info podman-compose
Last metadata expiration check: 0:00:31 ago on Thu 02 Sep 2021 08:28:23 AM PDT.
Installed Packages
Name         : podman-compose
Version      : 0.1.7
Release      : 4.git20210129.fc34
Architecture : noarch
Size         : 125 k
Source       : podman-compose-0.1.7-4.git20210129.fc34.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Run docker-compose.yml using podman
URL          : https://github.com/containers/podman-compose
License      : GPLv2
Description  : An implementation of docker-compose with podman backend.
             : The main objective of this project is to be able to run docker-compose.yml
             : unmodified and rootless.
```

I'll give the Devel branch a try and get back to you.

**Comment by jfmatth** [comment]
Sadly, same issue.

```
(podman-compose) [jfmatth@fedora podman-compose]$ podman ps
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
(podman-compose) [jfmatth@fedora podman-compose]$ podman images
REPOSITORY                    TAG         IMAGE ID      CREATED       SIZE
localhost/podman-compose_web  latest      fda70167c465  21 hours ago  994 MB
docker.io/library/python      3           6f1289b1e6a1  45 hours ago  934 MB
docker.io/library/postgres    latest      29dd0a82ea20  2 weeks ago   322 MB
k8s.gcr.io/pause              3.5         ed210e3e4a5b  5 months ago  690 kB
(podman-compose) [jfmatth@fedora podman-compose]$ podman pod list
POD ID      NAME        STATUS      CREATED     INFRA ID    # OF CONTAINERS
(podman-compose) [jfmatth@fedora podman-compose]$ podman-compose run web django-admin startproject composeexample .
['podman', '--version', '']
using podman version: podman version 3.3.0
podman pod create --name=podman-compose --share net -p 8000:8000
45dee69f1b5df49bb301c43c04b13879ba7e283e840cf04b0c903cfff1993a9c
0
podman run --name=podman-compose_web_tmp4451 -i --pod=podman-compose --label io.podman.compose.config-hash=123 --label io.podman.compose.project=podman-compose --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=podman-compose --label com.docker.compose.project.working_dir=/home/jfmatth/development/podman-compose --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=web -v /home/jfmatth/development/podman-compose/.:/code --add-host db:127.0.0.1 --add-host podman-compose_db_1:127.0.0.1 --add-host web:127.0.0.1 --add-host podman-compose_web_1:127.0.0.1 --tty podman-compose_web django-admin startproject composeexample .
Traceback (most recent call last):
  File "/usr/local/bin/django-admin", line 8, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/startproject.py", line 21, in handle
    super().handle('project', project_name, target, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/templates.py", line 160, in handle
    with open(new_path, 'w', encoding='utf-8') as new_file:
PermissionError: [Errno 13] Permission denied: '/code/manage.py'
1
(podman-compose) [jfmatth@fedora podman-compose]$ podman-compose version
['podman', '--version', '']
using podman version: podman version 3.3.0
podman-composer version  0.1.7dev
podman --version 
podman version 3.3.0
```

**Comment by jfmatth** [comment]
My suspicion tells me this example isn't terribly valid, since the awesome-compose/django example works fine.  Ill keep doing some more research in getting this to work.

**Comment by jfmatth** [comment]
Never mind, the example doesn't work with docker, docker-compose on Fedora 34 either, so ill chalk it up to not working
