### ISSUE TITLE
Can't `up` or `build` anymore

### ISSUE THREAD

**Issue by chpio** [containers/podman-compose#34]
```sh
$ podman-compose build
Traceback (most recent call last):
  File "/home/thomas/bin/podman-compose", line 1094, in <module>
    main()
  File "/home/thomas/bin/podman-compose", line 1091, in main
    podman_compose.run()
  File "/home/thomas/bin/podman-compose", line 623, in run
    cmd(self, args)
  File "/home/thomas/bin/podman-compose", line 780, in wrapped
    return func(*args, **kw)
  File "/home/thomas/bin/podman-compose", line 848, in compose_build
    build_one(compose, args, cnt)
  File "/home/thomas/bin/podman-compose", line 820, in build_one
    if getattr(args, 'if_not_exists'):
AttributeError: 'Namespace' object has no attribute 'if_not_exists'
```

on current master (2246204a52b8)

**Comment by muayyad-alsadi** [comment]
Please confirm it's fixed

**Comment by muayyad-alsadi** [comment]
I've included a manual test for this case

https://github.com/containers/podman-compose/tree/master/tests/build

closed because it's fixed and released
