### ISSUE TITLE
Apache Airflow setup fails

### ISSUE THREAD

**Issue by oshanz** [containers/podman-compose#350]
### steps to reproduce: (taken from https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html)

- `curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.2.0/docker-compose.yaml'`
-  `podman-compose up`
```bash
Traceback (most recent call last):
  File "/home/oz/.local/bin/podman-compose", line 11, in <module>
    load_entry_point('podman-compose==0.1.7.dev0', 'console_scripts', 'podman-compose')()
  File "/home/oz/.local/lib/python3.8/site-packages/podman_compose.py", line 1511, in main
    podman_compose.run()
  File "/home/oz/.local/lib/python3.8/site-packages/podman_compose.py", line 857, in run
    cmd(self, args)
  File "/home/oz/.local/lib/python3.8/site-packages/podman_compose.py", line 1075, in wrapped
    return func(*args, **kw)
  File "/home/oz/.local/lib/python3.8/site-packages/podman_compose.py", line 1210, in compose_up
    subproc = compose.podman.run([], podman_command, podman_args)
  File "/home/oz/.local/lib/python3.8/site-packages/podman_compose.py", line 711, in run
    print(" ".join(cmd_ls))
TypeError: sequence item 57: expected str instance, int found

```

**Comment by muayyad-alsadi** [comment]
would you please test using latest devel branch
because the line having the problem seems different and I don't know were does it break

**Comment by oshanz** [comment]
@muayyad-alsadi  I've just tested on podman-compose 0.1.7dev, podman 3.3.1
glad to say this error does not exists anymore :tada: 
so I'll close the ticket.

however it throws
```bash
Last check result:
$ airflow db check
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
ModuleNotFoundError: No module named 'airflow'
```

similar to this issue https://github.com/apache/airflow/issues/14111
not sure where the issue is, I'll dig that later. thanks :slightly_smiling_face:

**Comment by doyoungim999** [comment]
I just tested on podman-compose1.0.3, podman 3.4.4 to run airflow. 
I got docker-compose.yaml : 
$curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.4.1/docker-compose.yaml'

$podman-compose --version
['podman', '--version', '']
using podman version: 3.4.4
podman-composer version  1.0.3
podman --version
podman version 3.4.4
exit code: 0

Is there any progress ?
