### ISSUE TITLE
podman-compose down does not stop services in reverse dependency order

### ISSUE THREAD

**Issue by juspence** [containers/podman-compose#353]
I have a docker-compose.yml file like below:

```
version: '3'

services:
  postgres:
    container_name: postgres
    hostname: postgres

  redis:
    container_name: redis
    hostname: redis

  django:
    container_name: django
    hostname: django
    depends_on:
      - postgres
      - redis
      - celery-beat

  celery-beat:
    container_name: celery-beat
    hostname: celery
    depends_on:
      - postgres
      - redis

  celery-slow:
    container_name: celery-slow
    depends_on:
      - celery-beat

  celery-fast:
    container_name: celery-fast
    depends_on:
      - celery-beat
```

Running podman-compose up starts containers in the correct order, based on their dependencies. In this example, that's postgres (first), redis, celery-beat, web, celery-slow, and celery-fast (last).

Running podman-compose down stops containers in the same order. This causes issues when a dependent service disappears before a task finishes.

For example, celery depends on postgres for storage and redis for communication. So when redis is stopped before celery, I see the below errors in logs, and any unsaved data is probably lost since the DB is already gone.

It would be better if containers were stopped in the reverse order of how they're started (reverse dependency order). In this example, that's celery-fast (first), celery-slow, web, celery-beat, redis, and postgres (last).

````
$ podman logs celery-slow
[2021-11-10 16:15:12,004: INFO/MainProcess] Connected to redis://redis:6379//
[2021-11-10 16:15:12,016: INFO/MainProcess] mingle: searching for neighbors
[2021-11-10 16:15:13,028: INFO/MainProcess] mingle: all alone
[2021-11-10 16:15:13,039: INFO/MainProcess] slow_worker@d6f969399058 ready.
[2021-11-10 16:15:13,744: INFO/MainProcess] sync with fast_worker@1986b3323345
[2021-11-10 16:15:14,236: INFO/MainProcess] sync with fast_worker@cd1f5412a8bf
# Above is from startup

# Below is from shutting Redis down before Celery
[2021-11-10 16:15:27,478: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.9/site-packages/celery/worker/loops.py", line 81, in asynloop
    next(loop)
  File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 1252, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 500, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 841, in _receive
    ret.append(self._receive_one(c))
  File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 851, in _receive_one
    response = c.parse_response()
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 3505, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 324, in read_response
    raw = self._buffer.readline()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 256, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

[2021-11-10 16:15:27,488: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error 111 connecting to redis:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2021-11-10 16:15:29,492: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error 111 connecting to redis:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2021-11-10 16:15:33,496: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error 111 connecting to redis:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)


worker: Warm shutdown (MainProcess)
````

**Comment by muayyad-alsadi** [comment]
please test

**Comment by juspence** [comment]
@muayyad-alsadi Containers are now stopped in the reverse order of how they're started, and I don't see error messages in logs anymore. Thank you for fixing!

**Comment by parkr** [comment]
I'm having trouble with this. My `runner` containers (2) need to unregister themselves with GitHub but the VPN container their traffic is tunneled through is getting shut down too quickly. I tried `podman compose down -v runner` but **it shuts down all the containers (not just the `runner` ones)** so I'm left with `podman stop <container_id>` for each runner, waiting for them to stop, then running `docker compose down -v` to shut down the tunnel.

This is my docker-compose.yaml:

```yaml
services:
  tunnel:
    image: docker.io/qmcgaw/gluetun
    networks:
    - runner_net
    env_file:
    - "tunnel.env"
    privileged: true
    cap_add:
    - NET_ADMIN
    deploy:
      mode: global
    healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

  runner:
    # Instead of 
    # image: my-image-name
    # We simply build the image we want:
    build: ./linux
    restart: always
    env_file: .env
    privileged: true
    depends_on:
      tunnel:
        condition: service_healthy
    network_mode: service:tunnel
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 600M
        reservations:
          memory: 128M
networks:
  runner_net:
    dns: 1.1.1.1
```
