### ISSUE TITLE
podman-compose --dry-run up crashes

### ISSUE THREAD

**Issue by mhjacks** [containers/podman-compose#355]
**Describe the bug**
podman-compose --dry-run up crashes on start:

```
% podman-compose --dry-run up  
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==0.1.7.dev0', 'console_scripts', 'podman-compose')())
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1726, in main
    podman_compose.run()
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1030, in run
    cmd(self, args)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1262, in wrapped
    return func(*args, **kw)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1416, in compose_up
    create_pods(compose, args)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1378, in create_pods
    if not strverscmp_lt(compose.podman_version, "3.4.0"):
AttributeError: 'PodmanCompose' object has no attribute 'podman_version'
```

This is on latest devel, which has been packaged for fedora.

**To Reproduce**
1. what is the content of the current working directory (ex. `docker-compose.yml`, `.env`, `Dockerfile`, ...etc.)
2. what is the sequence of commands you typed

**Expected behavior**

A list of commands that would be run to bring up the project

**Actual behavior**
The stacktrace demonstrated above

**Output**

```
$ podman-compose version
using podman version: 3.4.0
podman-composer version  0.1.7dev
podman --version 
podman version 3.4.0
```

**Environment:**
 - OS: Linux - Fedora 35
 - podman version: 3.4.1
 - podman compose version: 0.1.7dev

**Additional context**

**Comment by muayyad-alsadi** [comment]
please test

**Comment by mhjacks** [comment]
It does indeed.  Thanks!
