### ISSUE TITLE
KeyError: '_service'

### ISSUE THREAD

**Issue by Maj0rK** [containers/podman-compose#361]
**Describe the bug**

Occurs on 0.1.8 and newest devel. Worked with a older devel version.

```
['podman', '--version', '']
using podman version: 3.4.2
** excluding:  set()
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/podman_compose.py", line 1763, in main
    podman_compose.run()
  File "/usr/local/lib/python3.9/site-packages/podman_compose.py", line 1037, in run
    cmd(self, args)
  File "/usr/local/lib/python3.9/site-packages/podman_compose.py", line 1269, in wrapped
    return func(*args, **kw)
  File "/usr/local/lib/python3.9/site-packages/podman_compose.py", line 1433, in compose_up
    if cnt["_service"] in excluded:
KeyError: '_service'
```

If I install podman-compose from https://github.com/containers/podman-compose/archive/117b7fbb9e7185f3d1952a399f69608dedcefaab.zip it is working again. There must be a change after this commit that breaks it.

**To Reproduce**

```
version: '2'
services:
  database:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_USER=test123
      - MYSQL_PASSWORD=test123
      - MYSQL_DATABASE=test123
  redis:
    image: redis:5.0.7
    volumes:
      - redis:/data
    ports:
      - 6379:6379
volumes:
  mysql:
    driver: local
  redis:
    driver: local
```

`podman-compose -f docker-compose.yml -t cntnet up`

**Environment:**
 - OS: Mac
 - podman version: 3.4.2
 - podman compose version: 0.1.8 and latest devel

**Comment by muayyad-alsadi** [comment]
I've just published a fix 0.1.9 on 0.1.x branch and devel branch.

please also note that we are working on a new way on 1.x branch
please have a look at that branch.
