### ISSUE TITLE
Type error thrown: unhashable type 'dict', when building a service

### ISSUE THREAD

**Issue by hammerfunctor** [containers/podman-compose#368]
**Describe the bug**
I followed the description given at https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md to install sharelatex, and got stuck when images were cloned.

I installed `podman-compose-git` from AUR just now to confirm this problem does not result from the outmoded version.

**To Reproduce**
1. clone https://github.com/overleaf/toolkit.git
2. run `bin/init` and `bin/up`

**Expected behavior**
service is built and server gets up

**Actual behavior**
`TypeError: unhashable type: 'dict'`

**Output**

```
# huzf @ arch-yoga in ~/code-demo/docker/sharelatex/overleaf on git:master x
$ bin/up
['podman', '--version', '']
using podman version: 3.4.2
 ** merged:
 {
  "_dirname": "/home/huzf/code-demo/docker/sharelatex/overleaf/lib",
  "version": "2.2",
  "services": {
    "sharelatex": {
      "restart": "always",
      "image": "sharelatex/sharelatex:3.0.1",
      "container_name": "sharelatex",
      "volumes": [
        "/home/huzf/code-demo/docker/sharelatex/data/sharelatex:/var/lib/sharelatex"
      ],
      "ports": [
        "80:80"
      ],
      "environment": {
        "SHARELATEX_MONGO_URL": "mongodb://mongo/sharelatex",
        "SHARELATEX_REDIS_HOST": "redis",
        "REDIS_HOST": "redis"
      },
      "env_file": [
        "../config/variables.env"
      ],
      "depends_on": {
        "redis": {
          "condition": "service_started"
        },
        "mongo": {
          "condition": "service_healthy"
        }
      },
      "links": [
        "redis",
        "mongo"
      ]
    },
    "redis": {
      "restart": "always",
      "image": "redis:5.0",
      "volumes": [
        "/home/huzf/code-demo/docker/sharelatex/data/redis:/data"
      ],
      "container_name": "redis",
      "expose": [
        6379
      ]
    },
    "mongo": {
      "restart": "always",
      "image": "mongo:4.0",
      "container_name": "mongo",
      "volumes": [
        "/home/huzf/code-demo/docker/sharelatex/data/mongodb:/data/db"
      ],
      "expose": [
        27017
      ],
      "healthcheck": {
        "test": "echo 'db.stats().ok' | mongo localhost:27017/test --quiet",
        "interval": "10s",
        "timeout": "10s",
        "retries": 5
      }
    }
  }
}
Traceback (most recent call last):
  File "/home/huzf/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==0.1.9', 'console_scripts', 'podman-compose')())
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 1787, in main
    podman_compose.run()
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 1047, in run
    self._parse_compose_file()
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 1141, in _parse_compose_file
    flat_deps(services, with_extends=True)
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 861, in flat_deps
    deps.update(deps_ls)
TypeError: unhashable type: 'dict'
```

**Environment:**
 - OS: Linux
 - podman version: 3.4.2
 - podman compose version: e879529

**Comment by muayyad-alsadi** [comment]
fixed in latest devel
