### ISSUE TITLE
podman-compose requires nonexistent `podman network exists` command

### ISSUE THREAD

**Issue by Infinoid** [containers/podman-compose#373]
`podman-compose` 1.0.2 attempts to use `podman network exists`, which is not a recognized subcommand in podman 3.0.1.

Steps to reproduce:

* fresh debian bullseye installation
* install podman using `apt`
* install podman-compose using `venv` and `pip3`
* put any `docker-compose.yml` file in a temp folder
* run `podman-compose up` as root

I did not try rootless yet; was trying to see basic operation first.

The expectation was that it would attempt to set up the containers described in the `docker-compose.yml` file.

What actually happened was that it tried and failed to run `podman network exists tmp_default`, and died with an exception.
It interprets a "that command doesn't exist" error as if it were saying "nope, that network doesn't exist", and then continues running.

On the first attempt, it creates the network and then dies when trying to verify its existence (by calling "network exists" again).
On subsequent attempts, it dies when trying to create an already existing network.

**Output**

```sh
# cat docker-compose.yml
version: "3"
services:
  test:
    image: busybox
    container_name: test

# podman-compose up
['podman', '--version', '']
using podman version: 3.0.1
** excluding:  set()
podman network exists 'tmp_default' || podman network create 'tmp_default'
['podman', 'network', 'exists', 'tmp_default']
Error: unrecognized command `podman network exists`
Try 'podman network --help' for more information.
['podman', 'network', 'create', '--label', 'io.podman.compose.project=tmp', '--label', 'com.docker.compose.project=tmp', 'tmp_default']
Error: the network name tmp_default is already used
Traceback (most recent call last):
  File "/home/infinoid/workspace/splash-docker/tmp/venv/lib/python3.9/site-packages/podman_compose.py", line 559, in assert_cnt_nets
    try: compose.podman.output([], "network", ["exists", net_name])
  File "/home/infinoid/workspace/splash-docker/tmp/venv/lib/python3.9/site-packages/podman_compose.py", line 809, in output
    return subprocess.check_output(cmd_ls)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['podman', 'network', 'exists', 'tmp_default']' returned non-zero exit status 125.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/infinoid/workspace/splash-docker/tmp/venv/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/home/infinoid/workspace/splash-docker/tmp/venv/lib/python3.9/site-packages/podman_compose.py", line 1738, in main
    podman_compose.run()
  File "/home/infinoid/workspace/splash-docker/tmp/venv/lib/python3.9/site-packages/podman_compose.py", line 1009, in run
    cmd(self, args)
  File "/home/infinoid/workspace/splash-docker/tmp/venv/lib/python3.9/site-packages/podman_compose.py", line 1233, in wrapped
    return func(*args, **kw)
  File "/home/infinoid/workspace/splash-docker/tmp/venv/lib/python3.9/site-packages/podman_compose.py", line 1399, in compose_up
    podman_args = container_to_args(compose, cnt, detached=args.detach)
  File "/home/infinoid/workspace/splash-docker/tmp/venv/lib/python3.9/site-packages/podman_compose.py", line 634, in container_to_args
    assert_cnt_nets(compose, cnt)
  File "/home/infinoid/workspace/splash-docker/tmp/venv/lib/python3.9/site-packages/podman_compose.py", line 571, in assert_cnt_nets
    compose.podman.output([], "network", args)
  File "/home/infinoid/workspace/splash-docker/tmp/venv/lib/python3.9/site-packages/podman_compose.py", line 809, in output
    return subprocess.check_output(cmd_ls)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['podman', 'network', 'create', '--label', 'io.podman.compose.project=tmp', '--label', 'com.docker.compose.project=tmp', 'tmp_default']' returned non-zero exit status 125.

# podman network --help
Manage networks

Description:
  Manage networks

Usage:
  podman network [command]

Available Commands:
  connect     network connect
  create      network create
  disconnect  network rm
  inspect     network inspect
  ls          network list
  reload      Reload firewall rules for one or more containers
  rm          network rm

# podman-compose --version
['podman', '--version', '']
using podman version: 3.0.1
podman-composer version  1.0.2
podman --version 
podman version 3.0.1
exit code: 0

# podman info
host:
  arch: arm64
  buildahVersion: 1.19.6
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 16
  distribution:
    distribution: debian
    version: "11"
  eventLogger: journald
  hostname: splash.infinoid.oi
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.7+
  linkmode: dynamic
  memFree: 32889610240
  memTotal: 65136394240
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 21474832384
  swapTotal: 21474832384
  uptime: 109h 29m 57.99s (Approximately 4.54 days)
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Wed Dec 31 19:00:00 1969
  GitCommit: ""
  GoVersion: go1.15.9
  OsArch: linux/arm64
  Version: 3.0.1
```

**Comment by muayyad-alsadi** [comment]
for versions of podman that does not support that please use podman-compose 0.1.x

quote from README.md

```
If you have legacy version of podman (before 3.x) you might need to stick with legacy podman-compose 0.1.x branch. The legacy branch 0.1.x uses mappings and workarounds to compensate for rootless limitations.
```

**Comment by muayyad-alsadi** [comment]
@Infinoid do you know the exact version podman started to have that command?

**Comment by Infinoid** [comment]
The git tag says 3.1.0-rc1.

https://github.com/containers/podman/commit/a45d22a1ddd2840cf8c3a38540aa8683cc0d5c7d

**Comment by muayyad-alsadi** [comment]
for your case you can use the legacy version like this.

```
$ pip3 install --user 'podman-compose<1.0'
```

**Comment by Infinoid** [comment]
Ok.  You may want to update your README.md - it says 3.x, but 3.0.x doesn't work.

Thanks!

**Comment by Infinoid** [comment]
Judging from https://repology.org/project/podman/versions, it's probably only CentOS 8, Debian 11 and Ubuntu 21.04 users who would be affected by this.

**Comment by muayyad-alsadi** [comment]
> Ok. You may want to update your README.md - it says 3.x, but 3.0.x doesn't work.

sure, I've just did. 

but it also says

> Modern podman versions (>=3.4) do not have those limitations and thus you can use latest and stable 1.x branch.

I'm using 3.4.2 on fedora.

**Comment by fauust** [comment]
Hi!
Confirmed on Debian11 with:
```console
❯ dpkg -l | grep podman
ii  podman                                           3.0.1+dfsg1-3+b2                amd64        engine to run OCI-based containers in Pods
```

Workaround: install version `0.1.11`.

**Comment by muayyad-alsadi** [comment]
yes, upgrade podman to +v3.1 or downgrade podman-compose to 0.1.x
