### ISSUE TITLE
podman-compose exec output messed up with command std output

### ISSUE THREAD

**Issue by bam80** [containers/podman-compose#380]
Consider following example:
```
$ cat cmake
#!/bin/sh

exec podman-compose exec toolchain cmake $@
```
If we run it, we get following output:
```
$ ./cmake --version 
['podman', '--version', '']
using podman version: 3.2.1
podman exec --interactive --tty --env QEMU_LD_PREFIX=/root/Develop/pinephone-manjaro-sysroot --env CMAKE_GENERATOR=Ninja --env NINJA_STATUS=[%p/%f/%t %e]  sdk_toolchain_1 cmake --version
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
exit code: 0
```
So the `podman-compose` output is messed up with `cmake` output.

That's probably the reason why such script isn't accepted by QtCreator as valid cmake.
This one works, though:
```
#!/bin/sh

exec podman exec sdk_toolchain_1 cmake $@
```

The `podman-compose` output should be redirected to stderr instead.

**Comment by muayyad-alsadi** [comment]
I totally agree

we needed that output in the past, maybe it's time to have a verbose flag too

I'll try to remove all prints to stdout and replace them with stderr this weekend

**Comment by muayyad-alsadi** [comment]
@bam80 please try latest devel branch and confirm

you can install it rootless using

```
pip3 install --user https://github.com/containers/podman-compose/archive/devel.tar.gz
```

**Comment by bam80** [comment]
Hmm, doesn't work for me:
```
$ cat cmake 
#!/bin/sh

podman start sdk_toolchain_1 >/dev/null
#podman exec -w "$PWD" -it sdk_toolchain_1 cmake $@
podman-compose exec sdk_toolchain_1 cmake
podman stop sdk_toolchain_1 >/dev/null

$ ./cmake 
['podman', '--version', '']
using podman version: 3.2.1
Traceback (most recent call last):
  File "/home/bam/.local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/home/bam/.local/lib/python3.9/site-packages/podman_compose.py", line 1797, in main
    podman_compose.run()
  File "/home/bam/.local/lib/python3.9/site-packages/podman_compose.py", line 1024, in run
    cmd(self, args)
  File "/home/bam/.local/lib/python3.9/site-packages/podman_compose.py", line 1248, in wrapped
    return func(*args, **kw)
  File "/home/bam/.local/lib/python3.9/site-packages/podman_compose.py", line 1554, in compose_exec
    container_names=compose.container_names_by_service[args.service]
KeyError: 'sdk_toolchain_1'

**Comment by muayyad-alsadi** [comment]
Pass service name not container name, 

```
podman-compose exec toolchain cmake
```

**Comment by bam80** [comment]
I still see the messed up output:
```
bam@Feedme:~/Develop/sdk$ ~/Develop/sdk/cmake 2>/dev/null 
['podman', '--version', '']
using podman version: 3.2.1
podman exec --interactive --tty --env QEMU_LD_PREFIX=/root/Develop/pinephone-manjaro-sysroot --env CMAKE_GENERATOR=Ninja --env NINJA_STATUS=[%p/%f/%t %e]  --env kdedir=None --env CMAKE_TOOLCHAIN_FILE=~/Develop/pinephone_toolchain.cmake --env CMAKE_CXX_COMPILER_LAUNCHER=ccache sdk_toolchain_1 cmake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.

exit code: 0

**Comment by bam80** [comment]
Any way I could see it actually upgraded?
```
bam@Feedme:~/Develop/sdk$ pip3 install --upgrade https://github.com/containers/podman-compose/archive/devel.tar.gz
Collecting https://github.com/containers/podman-compose/archive/devel.tar.gz
  Using cached https://github.com/containers/podman-compose/archive/devel.tar.gz
Requirement already satisfied: python-dotenv in /home/bam/.local/lib/python3.9/site-packages (from podman-compose==1.0.3) (0.19.2)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from podman-compose==1.0.3) (5.3.1)
bam@Feedme:~/Develop/sdk$ podman-compose version
['podman', '--version', '']
using podman version: 3.2.1
podman-composer version  1.0.3
podman --version 
podman version 3.2.1
exit code: 0

**Comment by muayyad-alsadi** [comment]
Are you sure you are using latest devel brach?

**Comment by bam80** [comment]
> you can install it rootless using
> 
> ```
> pip3 install --user https://github.com/containers/podman-compose/archive/devel.tar.gz
> ```

As seen above, I did exactly this

**Comment by muayyad-alsadi** [comment]
In your cmake shell script
You can debug envs like this

```bash
#! /bin/bash
set >/tmp/set
export >/tmp/export
which podman-compose >/tmp/which
# ...
exec ...
```

**Comment by bam80** [comment]
> you can install it rootless using
> 
> ```
> pip3 install --user https://github.com/containers/podman-compose/archive/devel.tar.gz
> ```

So that didn't work - I had to remove it before and reinstall again.

Then the output got separated:
```
bam@Feedme:~/Develop/sdk$ ~/Develop/sdk/cmake --version 
['podman', '--version', '']
using podman version: 3.2.1
podman exec --interactive --tty --env QEMU_LD_PREFIX=/root/Develop/pinephone-manjaro-sysroot --env CMAKE_GENERATOR=Ninja --env NINJA_STATUS=[%p/%f/%t %e]  --env kdedir=None --env CMAKE_TOOLCHAIN_FILE=~/Develop/pinephone_toolchain.cmake --env CMAKE_CXX_COMPILER_LAUNCHER=ccache sdk_toolchain_1 cmake --version
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
exit code: 0

bam@Feedme:~/Develop/sdk$ ~/Develop/sdk/cmake --version 2>/dev/null 
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
Strange thing I can't still make it work for Qt Creator:

That one works:
```
#!/bin/sh
podman exec sdk_toolchain_1 cmake $@
```
And that doesn't :(
```
#!/bin/sh
podman-compose exec toolchain cmake $@
```

PS:
Ah, possibly because `podman-compose` can't run outside of the project dir (if not given -f option)...

Well, OK, I probably _could_ make it work, still I didn't get it what's the point to use `podman-compose exec` here if ``podman exec` works also?

**Comment by bam80** [comment]
So this works, just doesn't acceptable here because of the need of `-f` option:
```
podman-compose -f ~/Develop/sdk/compose.yml exec toolchain cmake $@

**Comment by muayyad-alsadi** [comment]
I've the following `/path/repo/tests/delme/compose.yml`
```yaml
services:
  web:
    image: busybox
    command: httpd -f 8090 -h /etc/
```

while 

```
$ cd /path/repo/tests/delme
$ /path/repo/podman_compose.py up -d
# .. #
$ /path/repo/podman_compose.py exec web whoami 2>/dev/null
root
$ cd /path/to/repo
$ ./podman_compose.py -f ./tests/delme/compose.yml exec web whoami 2>/dev/null
root
```

so it works in both inside and outside

why you need to pass -f because `podman-compose` need to know which project do you want, for example you might 10 stacks each one of them have a service called "web", the option -f is needed to know which web do you want, the web of wordpress stack or the web of django stack ..etc.

> Ah, possibly because podman-compose can't run outside of the project dir (if not given -f option)...

I'm not sure about you case, but if need 

```
#!/bin/bash
here=`dirname "$0"`
cd "$here"
podman-compose exec toolchain cmake "$@"
```

**Comment by bam80** [comment]
> here=`dirname "$0"`

Great idea, thanks!
One would still need to pass it in `-f` probably because `cmake` has to be run in proper directory.

Having that, I'm still not quite understand benefits of using `podman-compose exec` against just `podman exec` here..

**Comment by muayyad-alsadi** [comment]
there is no benefit.
it's just convenience

after all podman-compose is just a wrapper for the shown podman commands.

**Comment by bam80** [comment]
The only convenience for `exec` I can see here is using service name `toolchain` instead a container name `sdk_toolchain_1`.
Is it all or there is something else?
