### ISSUE TITLE
Cannot start elk compose file

### ISSUE THREAD

**Issue by DavutOzcan87** [containers/podman-compose#424]
**Describe the bug**
I am trying to start elk stack on podman compose as described here: https://www.elastic.co/guide/en/elastic-stack-get-started/8.0/get-started-stack-docker.html#_prepare_the_environment 
but it is giving error

**To Reproduce**
1. create docker compose file and paste content from link
2. create .env file and paste content from link, set passwords
3. podman compose up 

**Expected behavior**
ELK stack started

**Actual behavior**
➜  elasticsearch podman-compose up
['podman', '--version', '']
using podman version: 3.4.4
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/podman_compose.py", line 1763, in main
    podman_compose.run()
  File "/usr/local/lib/python3.9/site-packages/podman_compose.py", line 1035, in run
    self._parse_compose_file()
  File "/usr/local/lib/python3.9/site-packages/podman_compose.py", line 1129, in _parse_compose_file
    flat_deps(services, with_extends=True)
  File "/usr/local/lib/python3.9/site-packages/podman_compose.py", line 856, in flat_deps
    deps.update(deps_ls)
TypeError: unhashable type: 'dict'

**Output**

```
$ podman-compose version
using podman version: 3.4.4
podman-composer version  0.1.8


$ podman-compose up
...

```

**Environment:**
 - OS:  Mac
 - podman version: 3.4.4
 - podman compose version: (git hex)

**Additional context**

**Comment by muayyad-alsadi** [comment]
> podman-composer version  0.1.8

we have fixed this long long ago
would you please upgrade your podman-compose

```
pip3 install --upgrade podman-compose
```
