### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'no_cache'

### ISSUE THREAD

**Issue by RodrigoDornelles** [containers/podman-compose#428]
**Describe the bug**

Cache issues occasional command termination for related errors.

**To Reproduce**
1. creating docker-compose.yml
```
version: '3.2'

services:
  frontend:
    restart: always
    build: frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./uploads:/app/frontend/web/uploads
      - ./:/app
      
  ## continue ...
```

2. creating Dockerfile in frontend/
```
FROM yiisoftware/yii2-php:8.0-apache

# Change configs
RUN echo "short_open_tag=On" > /usr/local/etc/php/conf.d/conf-short-tag.ini
RUN echo "upload_max_filesize = 100M\npost_max_size = 150M" > /usr/local/etc/php/conf.d/conf-max-size.ini

# Change document root for Apache
RUN sed -i -e 's|/app/web|/app/frontend/web|g' /etc/apache2/sites-available/000-default.conf
```

4. run command
```
docker-compose run --rm frontend php init
```

**Expected behavior**
run script normally

**Actual behavior**
failed to start pod and command not worked

**Output**

```
rodrigo@linux:~/projects/pref$ docker version
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.6
Built:        Wed Dec 31 21:00:00 1969
OS/Arch:      linux/amd64
rodrigo@linux:~/projects/pref$ docker-compose run --rm frontend php init
['podman', '--version', '']
using podman version: 3.4.2
podman pod create --name=pref --share net --infra-name=pref_infra -p 21080:80 -p 20080:80
Error: error adding pod to state: name "pref" is in use: pod already exists
exit code: 125
** excluding:  set()
Traceback (most recent call last):
  File "/home/rodrigo/.local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/home/rodrigo/.local/lib/python3.8/site-packages/podman_compose.py", line 1763, in main
    podman_compose.run()
  File "/home/rodrigo/.local/lib/python3.8/site-packages/podman_compose.py", line 1037, in run
    cmd(self, args)
  File "/home/rodrigo/.local/lib/python3.8/site-packages/podman_compose.py", line 1269, in wrapped
    return func(*args, **kw)
  File "/home/rodrigo/.local/lib/python3.8/site-packages/podman_compose.py", line 1514, in compose_run
    compose.commands['up'](compose, up_args)
  File "/home/rodrigo/.local/lib/python3.8/site-packages/podman_compose.py", line 1269, in wrapped
    return func(*args, **kw)
  File "/home/rodrigo/.local/lib/python3.8/site-packages/podman_compose.py", line 1422, in compose_up
    compose.commands['build'](compose, build_args)
  File "/home/rodrigo/.local/lib/python3.8/site-packages/podman_compose.py", line 1269, in wrapped
    return func(*args, **kw)
  File "/home/rodrigo/.local/lib/python3.8/site-packages/podman_compose.py", line 1376, in compose_build
    build_one(compose, args, cnt)
  File "/home/rodrigo/.local/lib/python3.8/site-packages/podman_compose.py", line 1354, in build_one
    if args.no_cache:
AttributeError: 'Namespace' object has no attribute 'no_cache'
rodrigo@linux:~/projects/pref$ 
```

**Environment:**
 - OS:  linux 5.4.0-91
 - podman version:  3.4.2
 - podman compose version:  0.1.8

**Comment by RodrigoDornelles** [comment]
duplicated #393
