### ISSUE TITLE
ValueError on unknown service usage

### ISSUE THREAD

**Issue by husio** [containers/podman-compose#434]
When using `podman-compose` with an invalid (non existing) service name, `ValueError` or `KeyError` is returned.

```
% podman-compose exec xyz
['podman', '--version', '']
using podman version: 3.4.4
Traceback (most recent call last):
  File "/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.0.2', 'console_scripts', 'podman-compose')())
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1738, in main
    podman_compose.run()
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1009, in run
    cmd(self, args)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1233, in wrapped
    return func(*args, **kw)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1515, in compose_exec
    container_names=compose.container_names_by_service[args.service]
KeyError: 'xyz'
```

```
% podman-compose start xyz
['podman', '--version', '']
using podman version: 3.4.4
Traceback (most recent call last):
  File "/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.0.2', 'console_scripts', 'podman-compose')())
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1738, in main
    podman_compose.run()
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1009, in run
    cmd(self, args)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1233, in wrapped
    return func(*args, **kw)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1552, in compose_start
    transfer_service_status(compose, args, 'start')
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1541, in transfer_service_status
    raise ValueError("unknown service: " + service)
ValueError: unknown service: xyz
```

**Describe the bug**
Instead of a Python exception, I expect the program to exit with a human readable, helpful message, for example "service xyz is not defined".

**To Reproduce**
1. create a docker-compose that does not specify service `xyz`
2. run `podman-compose logs xyz`

**Environment:**
 - OS: Linux
```
% podman-compose version
['podman', '--version', '']
using podman version: 3.4.4
podman-composer version  1.0.2
podman --version
podman version 3.4.4
exit code: 0
```

**Comment by muayyad-alsadi** [comment]
this is related to that issue

https://github.com/containers/podman-compose/issues/411
