### ISSUE TITLE
Cannot run example

### ISSUE THREAD

**Issue by frgt10cs** [containers/podman-compose#448]
I use Debian 11. Installed podman-compose by pip. When i try to run your example or anything else i have error. What could be wrong?

```
$ ~/.local/bin/podman-compose up compose.yml
```

**['podman', '--version', '']
using podman version: 3.0.1
Traceback (most recent call last):
  File "/home/v-user/.local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/home/v-user/.local/lib/python3.9/site-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/home/v-user/.local/lib/python3.9/site-packages/podman_compose.py", line 1024, in run
    cmd(self, args)
  File "/home/v-user/.local/lib/python3.9/site-packages/podman_compose.py", line 1248, in wrapped
    return func(\*args, \*\*kw)
  File "/home/v-user/.local/lib/python3.9/site-packages/podman_compose.py", line 1394, in compose_up
    excluded = get_excluded(compose, args)
  File "/home/v-user/.local/lib/python3.9/site-packages/podman_compose.py", line 1387, in get_excluded
    excluded-= compose.services[service]['_deps']
KeyError: 'compose.yml'**

**Environment:**
 - OS: Linux (Debian 11)
 - podman version: 3.0.1
 - podman compose version: 1.0.3

**Comment by muayyad-alsadi** [comment]
Use --help to see how to run it

It does not take the yaml as argument

Sorry for the confusing message

**Comment by frgt10cs** [comment]
yes, sorry, my bad (:
