### ISSUE TITLE
Unable to create network with "networks" attribute

### ISSUE THREAD

**Issue by miburke** [containers/podman-compose#461]
Maybe not a bug, but I'm not sure what I'm doing wrong.  Perhaps it's not a supported feature yet?

I am unable to create a pod with a user-defined network via the "networks" attribute.  I need to create containers with static IPs and reading the compose spec, the networks and ipv4_address attribute appear to be the way to accomplish this.  My compose file is as follows:

```
version: "3"
networks:
  app1_container_network:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
services:
  app1:
    build: ./app1
    networks:
      app1_container_network:
        ipv4_address: 172.20.0.11

```
When I attempt to start the pod with `podman-compose up` I get the following error:

```
['podman', '--version', '']
using podman version: 3.4.4
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/usr/local/lib/python3.9/site-packages/podman_compose.py", line 1022, in run
    self._parse_compose_file()
  File "/usr/local/lib/python3.9/site-packages/podman_compose.py", line 1128, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: app1_container_network
```

1. podman-compose up

**Expected behavior**
Container starts connected to app1_container_network, and has IP 172.20.0.11

**Actual behavior**
Error noted above is output

**Output**

```
$ podman-compose version
['podman', '--version', '']
using podman version: 3.4.4
podman-composer version  1.0.3
podman --version 
podman version 3.4.4
exit code: 0

$ podman-compose up
...
['podman', '--version', '']
using podman version: 3.4.4
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/usr/local/lib/python3.9/site-packages/podman_compose.py", line 1022, in run
    self._parse_compose_file()
  File "/usr/local/lib/python3.9/site-packages/podman_compose.py", line 1128, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: app1_container_network

```

**Environment:**
 - OS: Linux (Fedora 33)
 - podman version: 3.4.4
 - podman compose version: (git hex)

**Comment by muayyad-alsadi** [comment]
Please upgrade to latest devel, we have fixed a similar bug in the past couple of days.

Side note: 
* do not treat containers as pets, don't care about their IPs. There are better ways ex.  [Host port mapping](https://12factor.net/port-binding) 
* Either let compose manage networks / volumes or you manage it yourself (that is called external) you create it and pass its name to compose.

**Comment by muayyad-alsadi** [comment]
here is the output with latest version

```yaml
---
version: "3"
networks:
  app1_container_network:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
services:
  app1:
    image: busybox
    command: httpd -f -p 8080 -h /etc/
    networks:
      app1_container_network:
        ipv4_address: 172.20.0.11
```

```
$ ../../podman_compose.py up
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 3.4.4
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=nets_test5', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
podman pod create --name=pod_nets_test5 --infra=false --share=
9a20760d3ab96ed9d7946bec76393d2853c512ae5aa7495d54f98d6766333b03
exit code: 0
['podman', 'network', 'exists', 'nets_test5_app1_container_network']
podman create --name=nets_test5_app1_1 --pod=pod_nets_test5 --label io.podman.compose.config-hash=d06a047db411a1f1bf2d8bdefb8a152132a4e0441893bba922a6901a46a72c57 --label io.podman.compose.project=nets_test5 --label io.podman.compose.version=1.0.4 --label com.docker.compose.project=nets_test5 --label com.docker.compose.project.working_dir=/home/alsadi/proj/podman-compose/tests/nets_test5 --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=app1 --net nets_test5_app1_container_network --network-alias app1 --ip=172.20.0.11 busybox httpd -f -p 8080 -h /etc/
32cf92683328041b47ed82a2753b8ba5f18ca70357a4a5a95dc8a14c00b20138
exit code: 0
podman start -a nets_test5_app1_1
```
