### ISSUE TITLE
Passing environment variables do not match docker-compose

### ISSUE THREAD

**Issue by ztane** [containers/podman-compose#491]
Given compose file

```
---
version: '3.7'
services:
  test:
    image: ubuntu:20.04
    container_name: ubuntu
    environment:
    - FOO
    command: bash -c 'set | grep FOO'
```

and having the `FOO` set in `.env`, the variable is not passed into the container. Using `- FOO=${FOO}` works but either one works with docker-compose.

podman-compose version: 1.0.4
using podman version: 3.4.2

**Comment by john-waczak** [comment]
Just ran into the same issue

**Comment by acteq** [comment]
agree

**Comment by idrisFoughali** [comment]
I've also run into this issue, including the fact that I can't map my variables to my docker-compose values.

Eg:
```yaml
---
version: '3.7'
services:
  test:
    image: $DIST:$VERSION
    container_name: $DIST
    environment:
    - FOO
```


This build would fail, as podman-compose fails to load the DIST and VERSION while attempting to spin up the container.

**Comment by l3ender** [comment]
We ran into issues when environment variables had quotes, e.g. `- FOO="abc"`. Once we removed quotes, the `- FOO=${FOO}` approach worked.

**Comment by xmnlab** [comment]
I had the same issue here.

I am used to use something like this with docker-compose:

```
ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
```

and it gets the value from the .env file:

```
env_file:
      - ../.env
```

with podman-compose it doesn't work.

but if I export this variable before I run the podman-compose command, it works just fine.

**Comment by devurandom** [comment]
When running `docker-compose -f docker-compose.yml -f docker-compose.extras.yml up` with these files:
```
# docker-compose.yml
version: "3.2"
services:
  srv:
    environment:
      - MY_VAR
```
and
```
# docker-compose.extras.yml
version: "3.2"
  srv:
    environment:
      - MY_VAR=value
```

I get:
```
['podman', '--version', '']
using podman version: 4.3.1
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.0.3', 'console_scripts', 'podman-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1774, in main
    podman_compose.run()
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1021, in run
    self._parse_compose_file()
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1090, in _parse_compose_file
    rec_merge(compose, content)
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 917, in rec_merge
    ret = rec_merge_one(target, source)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 907, in rec_merge_one
    rec_merge_one(value, value2)
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 907, in rec_merge_one
    rec_merge_one(value, value2)
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 907, in rec_merge_one
    rec_merge_one(value, value2)
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 895, in rec_merge_one
    raise ValueError("can't merge value of {} of type {} and {}".format(key, type(value), type(value2)))
ValueError: can't merge value of HOSTING_DOMAIN of type <class 'NoneType'> and <class 'str'>
```

**Comment by superev12** [comment]
Also have this issue. For `docker-compose.yaml` with the content
```
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
```

When running the container, 
POSTGRES_USER=user
POSTGRES_PASSWORD=pass
POSTGRES_DB=db

and port 5432 is instead mapped to 35432.

**Comment by Movion** [comment]
Any news for this? I also had the problem with podman-compose & mattermost **as root** when using variables

When im using the recommended [.env](https://github.com/mattermost/docker/blob/main/env.example) file example and change postgres information, it is not forwarded to the container.

**How to reproduce:** 
Use the env example file of mattermost, copy to .env, change the postgres information,:
```
POSTGRES_USER=mmuser
POSTGRES_PASSWORD=yourbelovedpassword
POSTGRES_DATABASE=mattermost
```

[docker-compose.yml](https://github.com/mattermost/docker/blob/main/docker-compose.yml) is having this information: 
```
      # necessary Postgres options/variables
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
```

When you hit the command to start:
` podman-compose --env-file=./.env -f docker-compose.yml -f docker-compose.nginx.yml up -d`

The containers are starting up, but the variables are not forwarded
Seeing in the logs of the postgres container:
![postgres mm db](https://github.com/containers/podman-compose/assets/47115788/54e242e5-9445-425e-977c-ed8f766c894b)

**Fix:**
It got fixed by adding the =${varibale} in the docker-compose.yml
```
      # necessary Postgres options/variables
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
```

Than it works.. had todo this to all other variables too. 

Docker also "recomment" todo this: https://docs.docker.com/compose/environment-variables/set-environment-variables/ 
> The result is similar to the one above but Compose gives you a warning if the DEBUG variable is not set in the shell environment.

**Comment by mokibit** [comment]
@ztane  thank you for opening an issue, it was fixed by: #1248.
@p12tic  this issue can be closed.

**Comment by p12tic** [comment]
Fixed in https://github.com/containers/podman-compose/pull/1248.

**Comment by mokibit** [comment]
@ifoughal I can not reproduce your problem anymore with this configuration:
1) `compose.yml` file (a copy of your example with added command):
```
version: '3.7'
services:
  test:
    image: $DIST:$VERSION
    container_name: $DIST
    environment:
        - FOO
    command: printenv
```
2) `.env` file (in the same directory where `compose.yml` file is):
```
FOO=AAAA
DIST=debian
VERSION=bookworm
```
3) Versions:
```
podman-compose version 1.4.0
podman version 4.9.3
```
These commands were executed:
```
podman-compose up -d
podman ps -a
```
`podman ps -a` gives output:
```
CONTAINER ID  IMAGE                              COMMAND           CREATED        STATUS        PORTS       NAMES
3c776510654a  docker.io/library/debian:bookworm  tail -F anything  4 seconds ago  Up 3 seconds              debian
```
Where it is clearly visible that `$DIST` and `$VERSION` (`IMAGE` and `NAMES` sections respectively) values were correctly interpolated from `.env` file.

The value of `environment:` variable `-FOO` is also directly taken from `.env` file and passed to a container environment (it was fixed by #1248).
`podman logs debian` output is:
```
container=podman
FOO=AAAA
HOME=/root
HOSTNAME=d3d858a22192
```
@ifoughal try to update your `podman-compose` to the newest `main` branch. If you see any other issues, please open a new bug report.
@xmnlab  your problem seems to be similar. The only difference is that you provide custom path to `.env` file through `env_file:`  in your `compose.yml`. If it is still not working, please open a new bug report.

Thank you for your contributions!

**Comment by mokibit** [comment]
> We ran into issues when environment variables had quotes, e.g. `- FOO="abc"`. Once we removed quotes, the `- FOO=${FOO}` approach worked.

I assumed @l3ender meant using string `- FOO="abc"` in `.env` file. Please clarify.
Under that assumption, I tested `podman-compose` with this configuration:
1) `.env` file (in the same directory where `compose.yml` file is) has a variable value as a string:
```
FOO="AAAA"
```
2) `compose.yml` file:
```
services:
  test:
    image: busybox
    environment:
      - FOO=$FOO
    command: printenv
```
In `compose.yml`  file I tested 3 different cases:
1. 
```
environment:
      - FOO=$FOO
```
2. 
```
environment:
      - FOO=${FOO}
```
3. 
```
environment:
      - FOO
```
All three cases worked as expected, `podman logs podman-compose_test_1` giving results:
```
FOO=AAAA
container=podman
HOME=/root
HOSTNAME=6870adc3a7f8
```
That is: `FOO` environment variable was correctly interpolated and passed to container's environment.
@l3ender if you still see (any other) problem, please open a new bug report.

**Comment by mokibit** [comment]
@devurandom I get a similar error when testing with your configuration, that is: more than one `compose.yaml` files, which have competing `environment:` variables.
The issue might be associated with environment variable precedence. Seems that `podman-compose` does not fully emulate the functionality of `docker-compose` yet.
Feel free to open a new bug report.

**Comment by mokibit** [comment]
@superev12 I can not reproduce your problem anymore, please rebase on the newest `main` branch, it should work as expected now.
When reproducing I got these results.
`compose.yml` file:
```
services:
    postgres:
        image: "postgres"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
        command: printenv
```
`.env` file (in same directory as `compose.yml`):
```
POSTGRES_USER=TEST1
POSTGRES_PASSWORD=TEST2
POSTGRES_DB=TEST3
```
Commands `podman-compose up -d` and `podman ps -a` were executed.
Output of `podman ps -a`:
```
CONTAINER ID  IMAGE                              COMMAND     CREATED        STATUS                    PORTS                   NAMES
926db2679960  docker.io/library/postgres:latest  printenv    4 seconds ago  Exited (0) 2 seconds ago  0.0.0.0:5432->5432/tcp  podman-compose_postgres_1
```
Where `ports` were set correctly.
Output of `podman logs podman-compose_postgres_1`:
```
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=postgres
<...>
```
Output is as expected: values from `.env` file were overridden with values provided by `environment:` in your `compose.yml` file.
If you see any other issues, please open a new bug report.
