### ISSUE TITLE
Need help with troubleshooting podman-compose error RuntimeError: missing networks: app_net

### ISSUE THREAD

**Issue by Noggin79s** [containers/podman-compose#565]
_['podman', '--version', '']
using podman version: 4.1.1
podman-composer version  1.0.3
podman --version
podman version 4.1.1_

When I am attempting to run sudo podman-compose up -d --build I am seeing the following error...
_['podman', '--version', '']
using podman version: 4.1.1
Traceback (most recent call last):
  File "/bin/podman-compose", line 11, in <module>
    load_entry_point('podman-compose==1.0.3', 'console_scripts', 'podman-compose')()
  File "/usr/lib/python3.6/site-packages/podman_compose.py", line 1774, in main
    podman_compose.run()
  File "/usr/lib/python3.6/site-packages/podman_compose.py", line 1021, in run
    self._parse_compose_file()
  File "/usr/lib/python3.6/site-packages/podman_compose.py", line 1127, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: app_net_

Looking up that error it was suggested that I upgrade to podman-compose 1.0.4

sudo pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
_WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting https://github.com/containers/podman-compose/archive/devel.tar.gz
  Downloading https://github.com/containers/podman-compose/archive/devel.tar.gz
     | 71kB 3.0MB/s
Requirement already satisfied: pyyaml in /usr/lib64/python3.6/site-packages (from podman-compose==1.0.4)
Requirement already satisfied: python-dotenv in /usr/lib/python3.6/site-packages (from podman-compose==1.0.4)
Installing collected packages: podman-compose
  Running setup.py install for podman-compose ... done
Successfully installed podman-compose-1.0.4_

However if I run podman-compose up -d --build I am still seeing the "RuntimeError: missing networks: app_net"

Any help would be appreicated.

**Comment by mokibit** [comment]
The original `docker-compose.yml` file was not included in this bug report. The analysis below is based on an assumption about what the file likely contained, inferred from the error message. Without the actual compose file, I cannot be 100% certain of the root cause.

Environment:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```
I created a minimal reproduction case to test the `missing networks: app_net` error.
`docker-compose.yml`:
```
services:
  test_service:
    image: busybox
    networks:
      - app_net
    command: ["sleep", "3600"]
```
Running `podman-compose up` with this file produces the exact same error the user reported:
```
RuntimeError: missing networks: app_net
```
**Assumed root cause**:
The error is raised by design in `podman_compose.py` during compose file parsing. The code validates that every network referenced by a service is also declared in the top-level `networks:` section of the compose file. If a service references `app_net` but the network is not declared, this error is raised.

**Likely solution**:
If your compose file looked like the reproduction case above (service references `app_net` but has no top-level `networks:` declaration), adding the following should resolve the issue:
```
services:
  test_service:
    image: busybox
    networks:
      - app_net
    command: ["sleep", "3600"]

networks:
  app_net:   # <-- Add this declaration
```
I verified that with this declaration in place, `podman-compose up` works correctly and creates the network automatically.

- If your compose file was missing the top-level `networks:` declaration, this issue can be closed as a configuration error.
- Related issues with additional context and solutions for the same error:
        https://github.com/containers/podman-compose/issues/584
        https://github.com/containers/podman-compose/issues/552#issuecomment-5479543590
- If your compose file already had the `networks:` declaration and you still saw this error even with the newest versions of `podman-compose`, please share the full `docker-compose.yml` and I will reopen the investigation.
