### ISSUE TITLE
Custom network cannot be parsed or used: RuntimeError: missing networks: ...

### ISSUE THREAD

**Issue by leiless** [containers/podman-compose#579]
### Env

```bash
$ cat /etc/os-release                             
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"

$ podman-compose version 
['podman', '--version', '']
using podman version: 3.4.2
podman-composer version  1.0.3
podman --version 
podman version 3.4.2
exit code: 0

$ podman version        
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.15.2
Built:        Thu Jan  1 08:00:00 1970
OS/Arch:      linux/amd64
```

### `docker-compose.yaml`

```yaml
---
version: '3'

services:
    app:
        image: docker.io/alpine:3.16
        networks:
            net:
                ipv4_address: 172.18.18.1
        command: ip addr

networks:
    net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.18.0/24
                - gateway: 172.18.18.254
```

### Unexpected `podman-compose up`

```bash
$ podman-compose up
['podman', '--version', '']
using podman version: 3.4.2
Traceback (most recent call last):
  File "/home/lei/.local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/home/lei/.local/lib/python3.8/site-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/home/lei/.local/lib/python3.8/site-packages/podman_compose.py", line 1022, in run
    self._parse_compose_file()
  File "/home/lei/.local/lib/python3.8/site-packages/podman_compose.py", line 1128, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: net
```

### If I replace the `services.app.networks` with `services.app.network_mode`, the networking settings still isn't working properly

```diff
diff --git a/docker-compose.yaml b/docker-compose-2.yaml
index a78c327..401c7d3 100644
--- a/docker-compose.yaml
+++ b/docker-compose-2.yaml
@@ -4,7 +4,7 @@ version: '3'
 services:
     app:
         image: docker.io/alpine:3.16
-        networks:
+        network_mode:
             net:
                 ipv4_address: 172.18.18.1
         command: ip addr
```

```bash
$ podman-compose -f docker-compose-2.yaml up 
['podman', '--version', '']
using podman version: 3.4.2
** excluding:  set()
['podman', 'network', 'exists', 't_net']
podman create --name=t_app_1 --label io.podman.compose.config-hash=123 --label io.podman.compose.project=t --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=t --label com.docker.compose.project.working_dir=/tmp/t --label com.docker.compose.project.config_files=docker-compose-2.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=app --network {'net': {'ipv4_address': '172.18.18.1'}} --net t_net --network-alias app docker.io/alpine:3.16 ip addr
f50eaf13ddf41b0c58e71df097fbfa47f734e688bf5d06629be40925b0c440df
exit code: 0
podman start -a t_app_1
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if7: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether c2:06:47:0e:f2:7d brd ff:ff:ff:ff:ff:ff
    inet 10.89.2.5/24 brd 10.89.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::c006:47ff:fe0e:f27d/64 scope link 
       valid_lft forever preferred_lft forever
exit code: 0

# UNEXPECTED subnet and gateway
$ docker network inspect t_net | jq '.[0] | .plugins[0] | .ipam | .ranges | .[0][0]'
{
  "gateway": "10.89.2.1",
  "subnet": "10.89.2.0/24"
}
```

Custom network `172.18.18.0/24` isn't working.

**Comment by leiless** [comment]
With the latest `podman-compose` (i.e. 1.0.4), the issue is gone.

```bash
$ podman-compose up
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 3.4.2
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=t', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
podman pod create --name=pod_t --infra=false --share=
5bbd9596c15c0554cf129345d875677f256ee39d664695f1e03a9fbcd7cbc547
exit code: 0
['podman', 'network', 'exists', 't_net']
['podman', 'network', 'create', '--label', 'io.podman.compose.project=t', '--label', 'com.docker.compose.project=t', '--driver', 'bridge', '--subnet', '172.18.18.0/24', '--gateway', '172.18.18.254', 't_net']
['podman', 'network', 'exists', 't_net']
podman create --name=t_app_1 --pod=pod_t --label io.podman.compose.config-hash=3e9b516b20dc1fbe865c36ad3542565a71ad7458f3b7afeb242bb8809b5c8739 --label io.podman.compose.project=t --label io.podman.compose.version=1.0.4 --label PODMAN_SYSTEMD_UNIT=podman-compose@t.service --label com.docker.compose.project=t --label com.docker.compose.project.working_dir=/tmp/t --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=app --net t_net --network-alias app --ip=172.18.18.1 docker.io/alpine:3.16 ip addr
6deeac86fd43b3ffe61225d0b91cf0d3934fe7ffe934dea49cccf1ae9b0a11c2
exit code: 0
podman start -a t_app_1
[app] | 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
[app] |     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
[app] |     inet 127.0.0.1/8 scope host lo
[app] |        valid_lft forever preferred_lft forever
[app] |     inet6 ::1/128 scope host 
[app] |        valid_lft forever preferred_lft forever
[app] | 2: eth0@if11: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
[app] |     link/ether 92:b1:d0:e5:76:55 brd ff:ff:ff:ff:ff:ff
[app] |     inet 172.18.18.1/24 brd 172.18.18.255 scope global eth0
[app] |        valid_lft forever preferred_lft forever
[app] |     inet6 fe80::90b1:d0ff:fee5:7655/64 scope link 
[app] |        valid_lft forever preferred_lft forever
exit code: 0

```

**Comment by midu16** [comment]
I am facing the same issue on the following environment: 

```bash
[root@inbacrnrdl0100 ~]# cat /etc/os-release
NAME="Fedora Linux"
VERSION="37 (Cloud Edition)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37 (Cloud Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f37/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
SUPPORT_END=2023-11-14
VARIANT="Cloud Edition"
VARIANT_ID=cloud
[root@inbacrnrdl0100 ~]# podman version
Client:       Podman Engine
Version:      4.4.1
API Version:  4.4.1
Go Version:   go1.19.5
Built:        Fri Feb 17 10:26:19 2023
OS/Arch:      linux/amd64
[root@inbacrnrdl0100 ~]# podman-compose version
['podman', '--version', '']
using podman version: 4.4.1
podman-composer version  1.0.3
podman --version
podman version 4.4.1
exit code: 0
[root@inbacrnrdl0100 ~]# podman-compose up -d
['podman', '--version', '']
using podman version: 4.4.1
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.0.3', 'console_scripts', 'podman-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1774, in main
    podman_compose.run()
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1021, in run
    self._parse_compose_file()
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1127, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: macvlan0
[root@inbacrnrdl0100 ~]# podman network ls
NETWORK ID    NAME        DRIVER
e57bee2276ab  macvlan0    macvlan
2f259bab93aa  podman      bridge
```
