### ISSUE TITLE
New flag --disable-default-network ?

### ISSUE THREAD

**Issue by paul-grozav** [containers/podman-compose#585]
**Is your feature request related to a problem? Please describe.**
For certain reasons I am blocked on this os/kernel
```bash
$ cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)
$ uname -a
Linux my-server 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

I don't know if upgrading podman(1.6.4) is an option, since I don't want lots of the OS packages to be upgraded.

For security reasons I'm running in rootless mode
```bash
$ podman network ls
Error: network list is not supported for rootless mode

$ podman info
host:
  BuildahVersion: 1.11.7
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.8-1.el7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.8, commit: f85c8b1ce77b73bcd48b2d802396321217008762'
  Distribution:
    distribution: '"centos"'
    version: "7"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 588
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 2115
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
  MemFree: 8209367040
  MemTotal: 67333496832
  OCIRuntime:
    name: runc
    package: containerd.io-1.4.3-3.1.el7.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc92
      commit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
      spec: 1.0.2-dev
  SwapFree: 2108923904
  SwapTotal: 2683281408
  arch: amd64
  cpus: 8
  eventlogger: file
  hostname: my-server
  kernel: 3.10.0-1160.76.1.el7.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.3-4.el7_8.x86_64
    Version: |-
      slirp4netns version 0.4.3
      commit: 2244b9b6461afeccad1678fac3d6e478c28b4ad6
  uptime: 131h 8m 5.12s (Approximately 5.46 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  ConfigFile: /home/dbadmin/.config/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-6.el7_8.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.6.1
        using FUSE kernel interface version 7.29
  GraphRoot: /home/dbadmin/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 5
  RunRoot: /run/user/2115/containers
  VolumePath: /home/dbadmin/.local/share/containers/storage/volumes
```
And I'm facing this problem:
```bash
$ cat docker-compose.yml
version: "3"
services:
  mariadb:
    image: mariadb:10.3.18
    environment:
    - MYSQL_ROOT_PASSWORD=something
networks: {}

$ podman-compose up
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 1.6.4
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=dbadmin', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']                                                                                                                                
podman pod create --name=pod_dbadmin --infra=false --share=
6692e966869d06e1485a84e238abc5f85c3c9580c22d352c2d718c48e5259ee9
exit code: 0
['podman', 'network', 'exists', 'dbadmin_default']
Error: unrecognized command `podman network exists`
Try 'podman network --help' for more information.
['podman', 'network', 'create', '--label', 'io.podman.compose.project=dbadmin', '--label', 'com.docker.compose.project=dbadmin', 'dbadmin_default']                                                                                                                            
Error: unknown flag: --label
Traceback (most recent call last):
  File "/home/dbadmin/.local/bin/podman-compose", line 696, in assert_cnt_nets
    compose.podman.output([], "network", ["exists", net_name])
  File "/home/dbadmin/.local/bin/podman-compose", line 1060, in output
    return subprocess.check_output(cmd_ls)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)        
subprocess.CalledProcessError: Command '['podman', 'network', 'exists', 'dbadmin_default']' returned non-zero exit status 125.
                 
During handling of the above exception, another exception occurred:
                                  
Traceback (most recent call last):              
  File "/home/dbadmin/.local/bin/podman-compose", line 2862, in <module>
    main()           
  File "/home/dbadmin/.local/bin/podman-compose", line 2858, in main
    podman_compose.run()        
  File "/home/dbadmin/.local/bin/podman-compose", line 1385, in run
    cmd(self, args)
  File "/home/dbadmin/.local/bin/podman-compose", line 1712, in wrapped
    return func(*args, **kw)
  File "/home/dbadmin/.local/bin/podman-compose", line 2023, in compose_up
    podman_args = container_to_args(compose, cnt, detached=args.detach)
  File "/home/dbadmin/.local/bin/podman-compose", line 865, in container_to_args
    assert_cnt_nets(compose, cnt)
  File "/home/dbadmin/.local/bin/podman-compose", line 737, in assert_cnt_nets
    compose.podman.output([], "network", args)
  File "/home/dbadmin/.local/bin/podman-compose", line 1060, in output
    return subprocess.check_output(cmd_ls)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['podman', 'network', 'create', '--label', 'io.podman.compose.project=dbadmin', '--label', 'com.docker.compose.project=dbadmin', 'dbadmin_default']' returned non-zero exit
 status 125.
```
**Describe the solution you'd like**
I managed to look a bit on the code, https://github.com/containers/podman-compose/blob/08ffcf6126a3ae4016e3d81e963a3629e4b75986/podman_compose.py#L800, and managed to apply a patch on it, that would workaround my problem.

Here's the patch:
```python
800c800
<         net_args.extend(["--net", net_names_str, "--network-alias", ",".join(aliases)])
---
>         net_args.extend([]) # "--net", net_names_str, "--network-alias", ",".join(aliases)])
1513a1514
>         self.default_net = None
```
I was thinking that maybe we could avoid using a default network, and add those net args, if a flag like `--disable-default-network` is set to true(would, of course, default to false).

I realize this might be an awkward setup that I have on the machine, especially with the old podman version which is running rootless with no support for networks. But I thought we might still want to keep the podman-compose script compatible with such CentOS7(latest kernel) systems. What do you guys think? Anyone else in my position?

Of course, the patch isn't complete, but it worked for my particular case.

**Describe alternatives you've considered**
Didn't think of alternative solutions, except, of course, stop using compose, and switch to `podman kube play` https://www.redhat.com/sysadmin/podman-play-kube-updates . But in my case it doesn't support ulimits, (which compose does support). I'm also considering switching to bash scripts to invoke the podman cmds that would bring up the stack/pod/containers.

**Additional context**
All details given in original description

**Comment by yuexiadudiao** [comment]
i meet this problem too, this problem really bothers me.

**Comment by muayyad-alsadi** [comment]
Is this fixed by #635 

https://github.com/containers/podman-compose/pull/635

**Comment by mokibit** [comment]
I can no longer reproduce this problem. 
Check the version:
```
podman-compose --version
podman-compose version 1.4.0
podman version 5.4.2
```
I tested it with this `compose.yml` file: 
```
version: "3"
services:
  mariadb:
    image: docker.io/library/mariadb:10.3.18
    environment:
    - MYSQL_ROOT_PASSWORD=something
networks: {}
```
The command `podman-compose up` succesfully creates a container even when `networks` is empty (`networks: {}`).
```
$ podman ps -a
CONTAINER ID  IMAGE                              COMMAND     CREATED        STATUS        PORTS       NAMES
3a0ac36f1199  docker.io/library/mariadb:10.3.18  mysqld      3 seconds ago  Up 3 seconds  3306/tcp    podman-compose_mariadb_1
```

@p12tic this issue can be closed.
