### ISSUE TITLE
Stdout fails to connect in podman-compose 1.0.4

### ISSUE THREAD

**Issue by JosephBrooksbank** [containers/podman-compose#598]
**Describe the bug**
When I run `podman-compose up --build` in v1.0.3, All of the stdouts from my containers properly attach to the terminal output. When I upgrade to the current `devel` version of podman-compose, I get the following python error instead:

```
podman start -a coi-ui
Exception in thread coi-ui:
Traceback (most recent call last):
  File "C:\Users\joebr\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\joebr\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\joebr\AppData\Local\Programs\Python\Python311\Lib\site-packages\podman_compose.py", line 1098, in run
    _ = subprocess.Popen(
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\joebr\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\joebr\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1491, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Running in windows. I believe this has something to do with the log formatter introduced in https://github.com/containers/podman-compose/pull/419
```
podman-compose -v
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.3.1
podman-compose version 1.0.4
podman --version
podman version 4.3.1
exit code: 0
```

please try to reproduce the bug in latest devel branch ✅

**To Reproduce**
1. using **'busybox' example compose file from this repo**
2. run `podman-compose up --build` in powershell on windows 11

**Expected behavior**
The output from stdout in the container attaches to the stdout of my terminal with no errors

**Actual behavior**
The error from above

**Environment:**
 - OS: WSL
 - podman version: 4.3.1
 - podman compose version: (git hex) 08ffcf6126a3ae4016e3d81e963a3629e4b75986

**Comment by bam80** [comment]
Still actual?
