### ISSUE TITLE
KeyError: "netw={'ipv4_address': '1.2.3.4'}"

### ISSUE THREAD

**Issue by devurandom** [containers/podman-compose#604]
**Describe the bug**

In docker-compose it appears to be possible to specify additional attributes the network of a service, cf. `srv2` in:
```docker-compose.yml
# test.yml
version: "3.2"
services:
  srv1:
    networks:
    - netw
  srv2:
    networks:
      netw:
	 ipv4_address: "172.21.2.3"
networks:
  netw:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "172.21.0.0/16"
```

But trying to `podman-compose -f test.yml up` this yields:
```
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.0.3', 'console_scripts', 'podman-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1774, in main
    podman_compose.run()
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1023, in run
    cmd(self, args)
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1247, in wrapped
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1414, in compose_up
    podman_args = container_to_args(compose, cnt, detached=args.detach)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 644, in container_to_args
    assert_cnt_nets(compose, cnt)
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 557, in assert_cnt_nets
    net_desc = nets[net] or {}
               ~~~~^^^^^
KeyError: "netw={'ipv4_address': '172.21.2.3'}"
```

Removing `srv1` (commenting out all three lines) yields another error:
```
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.0.3', 'console_scripts', 'podman-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1774, in main
    podman_compose.run()
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1021, in run
    self._parse_compose_file()
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1127, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: netw
```

**To Reproduce**
1. `podman-compose -f test.yml up` with `test.yml` being the YAML file quoted above.

**Expected behavior**

`srv2` is part of the `netw` network and uses IPv4 address `172.21.2.3` within that network.

**Actual behavior**

`KeyError` (or `RuntimeError`) as quoted above.

**Output**

```
$ podman-compose version
['podman', '--version', '']
using podman version: 4.3.1
podman-composer version  1.0.3
podman --version
podman version 4.3.1
exit code: 0
```

**Environment:**
 - OS: Linux
 - podman version: 4.3.1
 - podman compose version: 1.0.3

**Comment by muayyad-alsadi** [comment]
I believe this issue is solved, please try latest stable version 1.0.6

**Comment by mokibit** [comment]
I can no longer reproduce this issue with the current version of `podman-compose`:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```
`docker-compose.yml` (from the original bug report):
```
services:
  srv1:
    networks:
    - netw
  srv2:
    networks:
      netw:
        ipv4_address: "172.21.2.3"
networks:
  netw:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "172.21.0.0/16"
```
`podman-compose config` now parses the file successfully and produces output identical to `docker compose config`:
```
$ podman-compose config
networks:
  netw:
    driver: bridge
    ipam:
      config:
      - subnet: 172.21.0.0/16
      driver: default
services:
  srv1:
    networks:
    - netw
  srv2:
    networks:
      netw:
        ipv4_address: 172.21.2.3
```
Full `up` workflow also works once the minimal required `image` field is added (which `docker-compose` also requires):
```
services:
  srv1:
    image: busybox
    command: ["sleep", "3600"]
    networks:
    - netw
  srv2:
    image: busybox
    command: ["sleep", "3600"]
    networks:
      netw:
        ipv4_address: "172.21.2.3"
networks:
  netw:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "172.21.0.0/16"
```
```
$ podman-compose up -d
[ network created, both containers started ]

$ podman inspect test-podman-compose_srv2_1 --format '{{json .NetworkSettings.Networks}}'
{
    "test-podman-compose_netw":  { 
        "EndpointID":"",
        "Gateway":"172.22.0.1",
        "IPAddress":"172.22.2.3",
        "IPPrefixLen":16, 
        ...
    }
}

$ podman exec test-podman-compose_srv2_1 ip addr show eth0 
...
inet 172.22.2.3/16 brd 172.22.255.255 scope global eth0
...
```
`podman-compose up` no longer crashes during parsing. It proceeds to the actual container/network creation stage, generating the correct `podman network create` command with the subnet and driver from the compose file.

Closing as resolved.
