### ISSUE TITLE
Dockerfile not found in https://user:password@git/Test/frontend.git

### ISSUE THREAD

**Issue by 53845714nF** [containers/podman-compose#606]
**Describe the bug**
Fail when i run `podman-compose up`

**To Reproduce**
In my `docker-compose.yml`  i use this:
```
frontend:
    image: frontend
    container_name: frontend
    build:
      context: https://user:password@git/Test/frontend.git
    restart: always
    ports:
    - "80:80"
```

**Expected behavior**
Start to build my Container with the Dockerfile from Git Repo.

**Actual behavior**
When I run `podman-compose up` i get this:

**Output**
```
['podman', '--version', '']
using podman version: 4.3.1
** excluding:  set()
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'nsfw']
Error: inspecting object: nsfw: image not known
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.0.3', 'console_scripts', 'podman-compose')())
  File "/usr/lib/python3/dist-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/usr/lib/python3/dist-packages/podman_compose.py", line 1024, in run
    cmd(self, args)
  File "/usr/lib/python3/dist-packages/podman_compose.py", line 1248, in wrapped
    return func(*args, **kw)
  File "/usr/lib/python3/dist-packages/podman_compose.py", line 1400, in compose_up
    compose.commands['build'](compose, build_args)
  File "/usr/lib/python3/dist-packages/podman_compose.py", line 1248, in wrapped
    return func(*args, **kw)
  File "/usr/lib/python3/dist-packages/podman_compose.py", line 1355, in compose_build
    build_one(compose, args, cnt)
  File "/usr/lib/python3/dist-packages/podman_compose.py", line 1328, in build_one
    raise OSError("Dockerfile not found in "+ctx)
OSError: Dockerfile not found in https://user:password@git/Test/frontend.git
```

```
$ podman-compose version
['podman', '--version', '']
using podman version: 4.3.1
podman-composer version  1.0.3
podman --version 
podman version 4.3.1
exit code: 0
...

```

**Environment:**
 - OS: Debian 11
 - podman version: 
 ```
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.4
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```
 - podman compose version: (git hex)

**Additional context**
I can imagine that there is a problem with the authentication on the Git server.  When I use `git clone ...` or `docker compose up`
i do not have any issue. Maybe there is a better way to write the compose file but this way worked fine for me.

**Comment by blambo10** [comment]
im experiencing the same issue

```
Client:       Podman Engine
Version:      4.6.1
API Version:  4.6.1
Go Version:   go1.20.10
Built:        Sat Nov 18 11:48:31 2023
OS/Arch:      linux/amd64

```

**Comment by 53845714nF** [comment]
I have started to build images from my Dockerfiles and upload them to repository. With GitHub you can do this well even with action that it does this automatically. And people can also download it from GitHub. At home, I have Gitea where you can also upload your images. As a next step, I switched to k3s.

Of course, this does not change the problem. It's just a workaround, but I can work well with it.

**Comment by reekol** [comment]
2026. having exactly the same issue. 
podman version 5.4.2
