### ISSUE TITLE
Error "ValueError: can't merge value of build of type <class 'str'> and <class 'dict'>;" caused by build property defined as a string value

### ISSUE THREAD

**Issue by peterkracik** [containers/podman-compose#612]
**Describe the bug**
If the `build` property in the `docker-compose.yml` is defined as a string, the `podman compose up` throws `ValueError: can't merge value of build of type <class 'str'> and <class 'dict'>;`
After some digging, I found out, that it has to be defined as a class

to reproduce:

in `docker-compose.yml`

**Actual behavior**
```yaml
my_service:
  build:  ./my_service_context_path
...
```
-> error: ValueError: can't merge value of build of type <class 'str'> and <class 'dict'>;`

```yaml
my_service:
  build:  
    context: ./my_service_context_path
...
```
-> works correctly.

**Expected behavior**
to be able to define build as a string value, which is supported by docker-compose

**Output**

```
$ podman-compose version
['podman', '--version', '']
using podman version: 4.3.1
podman-composer version  1.0.3
podman --version
podman version 4.3.1

$ podman-compose up
['podman', '--version', '']
using podman version: 4.3.1
Traceback (most recent call last):
  File "/opt/homebrew/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.0.3', 'console_scripts', 'podman-compose')())
  File "/opt/homebrew/Cellar/podman-compose/1.0.3_1/libexec/lib/python3.10/site-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/opt/homebrew/Cellar/podman-compose/1.0.3_1/libexec/lib/python3.10/site-packages/podman_compose.py", line 1022, in run
    self._parse_compose_file()
  File "/opt/homebrew/Cellar/podman-compose/1.0.3_1/libexec/lib/python3.10/site-packages/podman_compose.py", line 1091, in _parse_compose_file
    rec_merge(compose, content)
  File "/opt/homebrew/Cellar/podman-compose/1.0.3_1/libexec/lib/python3.10/site-packages/podman_compose.py", line 918, in rec_merge
    ret = rec_merge_one(target, source)
  File "/opt/homebrew/Cellar/podman-compose/1.0.3_1/libexec/lib/python3.10/site-packages/podman_compose.py", line 908, in rec_merge_one
    rec_merge_one(value, value2)
  File "/opt/homebrew/Cellar/podman-compose/1.0.3_1/libexec/lib/python3.10/site-packages/podman_compose.py", line 908, in rec_merge_one
    rec_merge_one(value, value2)
  File "/opt/homebrew/Cellar/podman-compose/1.0.3_1/libexec/lib/python3.10/site-packages/podman_compose.py", line 896, in rec_merge_one
    raise ValueError("can't merge value of {} of type {} and {}".format(key, type(value), type(value2)))

```

**Environment:**
 - OS: Mac
 - podman version: 4.3.1
 - podman compose version: 1.0.3

**Comment by muayyad-alsadi** [comment]
I believe this is already fixed, would you please test


```
pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
```

**Comment by peterkracik** [comment]
> I believe this is already fixed, would you please test
> 
> ```
> pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
> ```

it still seems to be an issue in this version 1.0.4:
```
podman-compose up -d
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.3.1
Traceback (most recent call last):
  File "/opt/homebrew/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/podman_compose.py", line 2858, in main
    podman_compose.run()
  File "/opt/homebrew/lib/python3.10/site-packages/podman_compose.py", line 1383, in run
    self._parse_compose_file()
  File "/opt/homebrew/lib/python3.10/site-packages/podman_compose.py", line 1461, in _parse_compose_file
    rec_merge(compose, content)
  File "/opt/homebrew/lib/python3.10/site-packages/podman_compose.py", line 1240, in rec_merge
    ret = rec_merge_one(target, source)
  File "/opt/homebrew/lib/python3.10/site-packages/podman_compose.py", line 1229, in rec_merge_one
    rec_merge_one(value, value2)
  File "/opt/homebrew/lib/python3.10/site-packages/podman_compose.py", line 1229, in rec_merge_one
    rec_merge_one(value, value2)
  File "/opt/homebrew/lib/python3.10/site-packages/podman_compose.py", line 1211, in rec_merge_one
    raise ValueError(
ValueError: can't merge value of build of type <class 'str'> and <class 'dict'>
```

**Comment by muayyad-alsadi** [comment]
I've just tested this compose which have string build and it worked

https://github.com/containers/podman-compose/blob/devel/tests/build/docker-compose.yml#L4


```yaml
---
version: "3"
services:
    web1:
      build: ./context
      image: my-busybox-httpd
      ports:
      - 8080:80
```

do you have a merge case `docker-compose.override.yml` or extend or something like that?

**Comment by romanblanco** [comment]
I've been getting similar error:

```
['podman', '--version', '']
using podman version: 4.3.1
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1022, in run
    self._parse_compose_file()
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1091, in _parse_compose_file
    rec_merge(compose, content)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 918, in rec_merge
    ret = rec_merge_one(target, source)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 908, in rec_merge_one
    rec_merge_one(value, value2)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 908, in rec_merge_one
    rec_merge_one(value, value2)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 896, in rec_merge_one
    raise ValueError("can't merge value of {} of type {} and {}".format(key, type(value), type(value2)))
ValueError: can't merge value of command of type <class 'str'> and <class 'list'>
```

@muayyad-alsadi's suggestion (https://github.com/containers/podman-compose/issues/612#issuecomment-1369683328) works for me :+1:

**Comment by sbadakhc** [comment]
This one is a problem for me also. Any chance of a fix?

**Comment by muayyad-alsadi** [comment]
the fix is merged, please test it

**Comment by mokibit** [comment]
I cannot reproduce this issue. I tested the configuration below: 
Check the versions:
```
podman-compose --version
podman-compose version 1.4.0
podman version 5.4.2
```
1) `compose.yml` (the `build` property is provided as a string):
```
version: "3"
services:
    web1:
      build: "./context"
      image: my-busybox-httpd
      ports:
      - 8080:80
```
2) `context/Dockerfile`:
```
FROM busybox
RUN mkdir -p /www && echo 'Hello world' >/www/index.html
EXPOSE 80
CMD ["httpd", "-f", "-v", "-h", "/www"]
```
3) Test steps:
I ran `podman-compose up --build` and checked `http://localhost:8080`. The page displayed “Hello world”.
This test confirms that the `build` property can now be provided as a string and works as expected. 


@p12tic this issue can be closed.
