### ISSUE TITLE
Missing log_formatter program on Windows 11 (sed.exe)

### ISSUE THREAD

**Issue by baalkor** [containers/podman-compose#648]
**Describe the bug**
sed utility is used to perform log_formatter operation, but is not present by default on Windows.
['sed', '-e', 's/^/\x1b[1;32m[directory] |\x1b[0m\\ /;']

The sed utility is not embedded by default on Windows but can be installed inside [gnuwin32 package](https://gnuwin32.sourceforge.net/packages/sed.htm) 

NOTE: sed bin directory must be added to user's Path.

**To Reproduce**

On Windows 11 in cmd.exe: 
podman-compose -f compose.yaml up

podman start -a directory
Exception in thread directory:
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\UserNameTest\AppData\Roaming\Python\Python311\site-packages\podman_compose.py", line 1098, in run
    _ = subprocess.Popen(
        ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python311\Lib\subprocess.py", line 1491, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Environment:**
$ podman-compose version
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.4.1
podman-compose version 1.0.4
podman --version
podman version 4.4.1
exit code: 0

**Comment by muayyad-alsadi** [comment]
please test and tell me if it works
