### ISSUE TITLE
Support act and developer-friendly environment improvements/suggestions

### ISSUE THREAD

**Issue by bugfest** [containers/podman-compose#657]
**Describe the bug**

| Problem | Solution proposal |
| -------- | ------------------ |
| Pytest, Flake8 and Pylint are used during the build process but currently running these workflows locally with `act` is not working.  | Install missing dependency and set `black` version to a fixed rev: `23.3.0` (current) | 
| Missing instructions on how to create a developer environment to contribute to this project.  | Create a "How to contribute" section in README.md |
| There are no _Developer_ requirements so that installing those tools is a manual work. | Add `extras_require` section in setup.py | Providing a more automatic way to run this testing/linting toolset in local dev envs could improve the quality of the code PR. | provide [pre-commit](https://pre-commit.com) integration by defining `.pre-commit-config.yaml` config |
| All github workflows have the same job name (`build`) so it's hard to limit the workflow execution to a particular one. | Split `black` & `pylint` steps in two separate jobs |

**To Reproduce**
```
# run workflows with act
$ act --list
act --list
Stage  Job ID  Job name  Workflow name  Workflow file  Events
0      build   build     Pylint         pylint.yml     push,pull_request
0      build   build     PyTest         pytest.yml     push,pull_request

Detected multiple jobs with the same job name, use `-W` to specify the path to the specific workflow.

$ act -W .github/workflows/pylint.yml
```

**Expected behavior**
Workflow steps to run and finish with tests/linting results

**Actual behavior**
Linting `pfs/black` step is not working with `act` due to a missing OS dependency (`python3.10-env`)

**Output**

```
$ act -W .github/workflows/pylint.yml
...
[Pylint/build-3]   ❌  Failure - Main psf/black@stable
| The virtual environment was not created successfully because ensurepip is not
| available.  On Debian/Ubuntu systems, you need to install the python3-venv
| package using the following command.
|
|     apt install python3.10-venv
|
| You may need to use sudo with that command.  After installing the python3-venv
| package, recreate your virtual environment.
|
| Failing command: ['/var/run/act/actions/psf-black@stable/.black-env/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
|
| Traceback (most recent call last):
|   File "/var/run/act/actions/psf-black@stable/action/main.py", line 16, in <module>
|     run([sys.executable, "-m", "venv", str(ENV_PATH)], check=True)
|   File "/usr/lib/python3.10/subprocess.py", line 524, in run
|     raise CalledProcessError(retcode, process.args,
| subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'venv', '/var/run/act/actions/psf-black@stable/.black-env']' returned non-zero exit status 1.
```

**Environment:**
 - OS: Linux
 - podman version: N/A
 - podman compose version: N/A

**Comment by bugfest** [comment]
Created PR #658 with the issue's mentioned proposals
