### ISSUE TITLE
CLI fails after calls to build_one function (general error)

### ISSUE THREAD

**Issue by bugfest** [containers/podman-compose#669]
**Describe the bug**
PR #586 breaks the CLI

**To Reproduce**
```
git clone https://github.com/containers/podman-compose.git
cd podman-compose
git checkout 9a08f85ffd08d84796af5e9d104c0b83c5490d81
python podman_compose.py -f tests/deps/docker-compose.yaml up
```

**Expected behavior**
No errors

**Actual behavior**
What is the behavior you actually got and that should not happen.

**Output**

```
$ python podman_compose.py version
podman-compose version: 1.0.7
['podman', '--version', '']
using podman version: 4.4.4
podman-compose version 1.0.7
podman --version
podman version 4.4.4
exit code: 0

$ python podman_compose.py -f tests/deps/docker-compose.yaml up
podman-compose version: 1.0.7
['podman', '--version', '']
using podman version: 4.4.4
** excluding:  set()
Traceback (most recent call last):
  File "/Users/hades/sources-shared/podman-compose/podman_compose.py", line 2974, in <module>
    main()
  File "/Users/hades/sources-shared/podman-compose/podman_compose.py", line 2970, in main
    podman_compose.run()
  File "/Users/hades/sources-shared/podman-compose/podman_compose.py", line 1447, in run
    cmd(self, args)
  File "/Users/hades/sources-shared/podman-compose/podman_compose.py", line 1778, in wrapped
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/Users/hades/sources-shared/podman-compose/podman_compose.py", line 2062, in compose_up
    compose.commands["build"](compose, build_args)
  File "/Users/hades/sources-shared/podman-compose/podman_compose.py", line 1778, in wrapped
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/Users/hades/sources-shared/podman-compose/podman_compose.py", line 2021, in compose_build
    exit(p.returncode)
         ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'returncode'
```

**Environment:**
 - OS: Mac
 - podman version: `4.4.4`
 - podman compose version: `9a08f85`

**Additional context**
n/a

**Comment by bugfest** [comment]
Hi @Akruidenberg; It should get solved once https://github.com/containers/podman-compose/pull/670 gets merged
