### ISSUE TITLE
podman-compose 1.0.7: `Error: unknown flag: --ipam-driver`

### ISSUE THREAD

**Issue by leiless** [containers/podman-compose#711]
**Describe the bug**
I have a test podman-compose file, and it cannot create the custom network.

**To Reproduce**

```yaml
version: '3'

services:
    app:
        # https://hub.docker.com/r/archivebox/archivebox/tags
        image: docker.io/archivebox/archivebox:dev
        restart: unless-stopped
        ports:
            - 127.0.0.1:8000:8000
        environment:
            # https://github.com/ArchiveBox/ArchiveBox/blob/master/archivebox/config.py
            - IN_DOCKER=True
            - ALLOWED_HOSTS=*
            - SAVE_ARCHIVE_DOT_ORG=False
            - PUBLIC_INDEX=False
            - PUBLIC_SNAPSHOTS=False
        networks:
            net:
                ipv4_address: 172.18.2.1
        command: server --quick-init 0.0.0.0:8000

networks:
    net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.2.0/24
                - gateway: 172.18.2.254
```

Type `podman-compose up` can reproduce this bug.

**Expected behavior**
The network should be created successfully.

**Actual behavior**
Create network thrown the `Error: unknown flag: --ipam-driver`.

**Output**

```
$ podman-compose version
podman-compose version: 1.0.7
['podman', '--version', '']
using podman version: 3.4.4
podman-compose version 1.0.7
podman --version 
podman version 3.4.4
exit code: 0

$ podman-compose up
podman-compose version: 1.0.7
['podman', '--version', '']
using podman version: 3.4.4
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=archivebox', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
podman pod create --name=pod_archivebox --infra=false --share=
Error: error adding pod to state: name "pod_archivebox" is in use: pod already exists
exit code: 125
['podman', 'network', 'exists', 'archivebox_net']
['podman', 'network', 'create', '--label', 'io.podman.compose.project=archivebox', '--label', 'com.docker.compose.project=archivebox', '--driver', 'bridge', '--ipam-driver', 'default', '--subnet', '172.18.2.0/24', '--gateway', '172.18.2.254', 'archivebox_net']
Error: unknown flag: --ipam-driver
Traceback (most recent call last):
  File "/home/foo/.local/lib/python3.10/site-packages/podman_compose.py", line 736, in assert_cnt_nets
    compose.podman.output([], "network", ["exists", net_name])
  File "/home/foo/.local/lib/python3.10/site-packages/podman_compose.py", line 1161, in output
    return subprocess.check_output(cmd_ls)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['podman', 'network', 'exists', 'archivebox_net']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/foo/.local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/home/foo/.local/lib/python3.10/site-packages/podman_compose.py", line 3086, in main
    podman_compose.run()
  File "/home/foo/.local/lib/python3.10/site-packages/podman_compose.py", line 1492, in run
    retcode = cmd(self, args)
  File "/home/foo/.local/lib/python3.10/site-packages/podman_compose.py", line 1868, in wrapped
    return func(*args, **kw)
  File "/home/foo/.local/lib/python3.10/site-packages/podman_compose.py", line 2198, in compose_up
    podman_args = container_to_args(compose, cnt, detached=args.detach)
  File "/home/foo/.local/lib/python3.10/site-packages/podman_compose.py", line 958, in container_to_args
    assert_cnt_nets(compose, cnt)
  File "/home/foo/.local/lib/python3.10/site-packages/podman_compose.py", line 779, in assert_cnt_nets
    compose.podman.output([], "network", args)
  File "/home/foo/.local/lib/python3.10/site-packages/podman_compose.py", line 1161, in output
    return subprocess.check_output(cmd_ls)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['podman', 'network', 'create', '--label', 'io.podman.compose.project=archivebox', '--label', 'com.docker.compose.project=archivebox', '--driver', 'bridge', '--ipam-driver', 'default', '--subnet', '172.18.2.0/24', '--gateway', '172.18.2.254', 'archivebox_net']' returned non-zero exit status 125.

```

**Environment:**
 - OS: Linux (x86_64)
 - podman version: 3.4.4

**Comment by leiless** [comment]
I used `git bisect` to find the bug, and it turns out that https://github.com/containers/podman-compose/commit/8625d7a4e8872da8acd8d6856cf7b26d14c8cd97 is the first problematic git commit.

```git
$ git bisect bad
8625d7a4e8872da8acd8d6856cf7b26d14c8cd97 is the first bad commit
commit 8625d7a4e8872da8acd8d6856cf7b26d14c8cd97
Author: Benedikt Braunger <bb@emlix.com>
Date:   Tue Feb 7 19:17:38 2023 +0100

    add ipam-driver support
    
    Signed-off-by: Benedikt Braunger <bb@emlix.com>

 podman_compose.py | 18 ++++++++++--------
 1 file changed, 10 insertions(+), 8 deletions(-)
```
