### ISSUE TITLE
Static ip address and a pod in podman-compose

### ISSUE THREAD

**Issue by zak-admin** [containers/podman-compose#720]
I know this is not a forum. But I am not sure where else to ask this question to get this answer. This could be an issue if it is really a issue and also could be a feature request if I had mentioned something that is not available yet.

I have all ready created a network `test` with subnet `10.2.5.0/16` and also have create a pod `test` for this compose setup. I was not able to find a way to define the pod. Anyway when I try to check the networking with the following part in docker-compose.yml

```bash
    networks:
      test:
        ipv4_address: '10.2.5.2'
networks:
  test:
    driver: bridge
    ipam:
      driver: test
      config:
        - subnet:  10.2.5.0/16 
```

I get an error.

```bash
['podman', '--version', '']
using podman version: 4.3.1
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.0.3', 'console_scripts', 'podman-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/usr/lib/python3/dist-packages/podman_compose.py", line 1022, in run
    self._parse_compose_file()
  File "/usr/lib/python3/dist-packages/podman_compose.py", line 1128, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: test
```

What is the right way to define them?

**Comment by zak-admin** [comment]
I tried another method 

```bash
version: '3.8'

services:
  nginx:
    image: 'nginx:latest'
    ports:
      - '8080:80'
    networks:
      test:
        ipv4_address: '10.89.0.7'

networks:
  test:
    external: true
```

This time network test was created without any subnet definitions.
This did not work error.

```bash
['podman', '--version', '']
using podman version: 4.3.1
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.0.3', 'console_scripts', 'podman-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/usr/lib/python3/dist-packages/podman_compose.py", line 1022, in run
    self._parse_compose_file()
  File "/usr/lib/python3/dist-packages/podman_compose.py", line 1128, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: test
```

but the same snippet did work inside a portainer that is setup to the same user for the users. that I was able to run by the following compose file.

```bash
version: '3.8'
services:
  portainer-ce:
    container_name: 'portainer-alpine'
    image: 'portainer/portainer-ce:alpine'
    volumes:
      - '/run/user/1001/podman/podman.sock:/var/run/docker.sock:Z'
      - './root/data:/data'
    ports:
      - '50000:9443'
    networks:
      - 'test'

networks:
  test:
    name: 'test'
```

It seems to be podman-compose is not able to find the existence of network test while portainer was successful.

**Comment by muayyad-alsadi** [comment]
Yhe spec is clear about this
Compose should not auto create external resources like volumes or networks.

**Comment by mokibit** [comment]
I can no longer reproduce this issue with the following configuration:
Environment:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```
I tested the Compose-managed network approach (letting Compose create the network), which works correctly.
`docker-compose.yml`:
```
services:
  test_service:
    image: busybox
    command: ["sleep", "3600"]
    networks:
      test:
        ipv4_address: '10.2.5.2'

networks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.5.0/16
```
Commands:
```
$ podman-compose up -d
<...>
test-podman-compose_test_service_1
$ podman-compose exec test_service ip a
<...>
2: eth0@if6: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue qlen 1000
    link/ether 4a:61:ac:fe:82:ed brd ff:ff:ff:ff:ff:ff
    inet 10.2.5.2/16 brd 10.2.255.255 scope global eth0
<...>
```
**Result**: `podman-compose up` succeeded without errors. The container was correctly attached to the test network and the static IPv4 address `10.2.5.2/16` was successfully assigned to eth0.
A pod was created automatically by `podman-compose` (named <project_name>_pod), so no manual pod creation is necessary.
If you created the network beforehand with `podman network create test`, use the `external: true` declaration instead:
```
services:
  test_service:
    image: busybox
    command: ["sleep", "3600"]
    networks:
      test:
        ipv4_address: '10.2.5.2'

networks:
  test:
    external: true
```
The current `podman-compose` version correctly parses the top-level `networks:` section and no longer raises a validation error. Static IP assignment on custom networks and automatic pod creation both work as expected.

Regarding manually created pods: the Docker Compose spec does not have a `pod:` top-level element. `podman-compose` handles pod creation automatically. If you need to disable this, use `--in-pod=false` or set `x-podman.in_pod: false` in the compose file.

I am closing this issue as resolved. If you still encounter this problem on a recent version, please feel free to reopen with updated details.
