### ISSUE TITLE
I was able to assign custom ip address through portainer but not by podman-compose

### ISSUE THREAD

**Issue by zak-admin** [containers/podman-compose#722]
I tried another method 

```bash
version: '3.8'

services:
  nginx:
    image: 'nginx:latest'
    ports:
      - '8080:80'
    networks:
      test:
        ipv4_address: '10.89.0.7'

networks:
  test:
    external: true
```

This time network test was created without any subnet definitions.
This did not work error.

```bash
['podman', '--version', '']
using podman version: 4.3.1
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.0.3', 'console_scripts', 'podman-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/usr/lib/python3/dist-packages/podman_compose.py", line 1022, in run
    self._parse_compose_file()
  File "/usr/lib/python3/dist-packages/podman_compose.py", line 1128, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: test
```

but the same snippet did work inside a portainer that is setup to the same user for the users. that I was able to run by the following compose file.

```bash
version: '3.8'
services:
  portainer-ce:
    container_name: 'portainer-alpine'
    image: 'portainer/portainer-ce:alpine'
    volumes:
      - '/run/user/1001/podman/podman.sock:/var/run/docker.sock:Z'
      - './root/data:/data'
    ports:
      - '50000:9443'
    networks:
      - 'test'

networks:
  test:
    name: 'test'
```

It seems to be podman-compose is not able to find the existence of network test while portainer was successful.

_Originally posted by @zak-admin in https://github.com/containers/podman-compose/issues/720#issuecomment-1622684288_

**Comment by mokibit** [comment]
I can no longer reproduce this issue with the following configuration:
Environment:
```
Debian GNU/Linux 13 (trixie)
Python 3.13.5
podman-compose version 1.6.0
podman version 5.4.2
```
Create the external network (with a subnet so static IPs work):
```
podman network create test --subnet 10.89.23.0/24
```
 `docker-compose.yml`:
```
services:
  nginx:
    image: 'docker.io/library/nginx:latest'
    ports:
      - '8080:80'
    networks:
      test:
        ipv4_address: '10.89.23.7'
networks:
  test:
    external: true
```
Run the container:
```
podman-compose up -d
```
Verify the static IP was assigned:
```
$ podman inspect test-podman-compose_nginx_1 --format '{{json .NetworkSettings.Networks}}'
{"test":
  {
    "EndpointID":"",
    "Gateway":"10.89.23.1",
    "IPAddress":"10.89.23.7",
     <...>
  }
}
```
Result: The container starts successfully and the static IP `10.89.23.7` is correctly assigned on the test network. No `RuntimeError: missing networks: test` is raised.

If anyone still encounters this problem on a recent release, please provide:
- `podman-compose --version`
- `podman --version`
- The exact `docker-compose.yml` causing the error
and we can reopen.
