### ISSUE TITLE
podman-compose failing to recognize named volume

### ISSUE THREAD

**Issue by aadityadhruv** [containers/podman-compose#746]
**Describe the bug**
I have a simple compose file, which uses a named volume. This is the compose file:
```
---
version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - UID=1000
      - GID=1000
    ports:
      - 8384:8384 #Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    volumes:
      - syncthing:/var/syncthing:Z
    user: "1000:1000"
    restart: unless-stopped

```
 Running `podman-compose up -d` with that compose file leads to the following error:
```RuntimeError: volume [syncthing] not defined in top level```.

I have run the equivalent `podman` command, and the named volume works just fine. The only difference here is that I have to change the named volume to be `syncthing_syncthing` since that is the actual name of the volume, while the `podman-compose` picks that up from the directory it is in.

**Expected behavior**

The container should just spin up, as it has with the normal `podman` command.
**Actual behavior**
The volume is not being read. 

**Output**

```
~/containers/syncthing $ podman-compose --dry-run up -d
podman-compose version: 1.0.6
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.0.6', 'console_scripts', 'podman-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 2940, in main
    podman_compose.run()
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1420, in run
    self._parse_compose_file()
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1627, in _parse_compose_file
    raise RuntimeError(
RuntimeError: volume [syncthing] not defined in top level


```

**Environment:**
 - OS: Fedora Linux 38
 - podman version:  4.6.1
 - podman compose version: 1.0.6 (f6dbce36181c44d0d08b6f4ca166508542875ce1)
**Additional context**
I believe the problem didn't exist in a previous version of `podman-compose`.

**Comment by fwsmit** [comment]
It seems that this was changed in https://github.com/containers/podman-compose/commit/154a51245ff2c5c8c3690d3a0035b710b69d0c3d (issue https://github.com/containers/podman-compose/issues/386). The [spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md#volumes) says that you should define a volume in the top-level volumes key if it's used by multiple services:

> If the mount is a host path and is only used by a single service, it can be declared as part of the service definition. To reuse a volume across multiple services, a named volume must be declared in the [top-level volumes key](https://github.com/compose-spec/compose-spec/blob/master/07-volumes.md).

 But now `podman-compose` also requires this when the volume is in only 1 service, as is your case.

For now you can fix it by adding the following at the end of your compose file:

```
volumes:
    syncthing:
```

**Comment by aadityadhruv** [comment]
That works! I didn't know about the spec change! Is the podman implementation intentional or just a bug?

**Comment by mluhmann** [comment]
It looks like a bug, lots of my compose will fail if I apply this update of podman-compose.
This shouldn't be needed if only one service uses the volume. At least this is what the spec specifies:

> If the mount is a host path and is only used by a single service, it can be declared as part of the service definition. To reuse a volume across multiple services, a named volume must be declared in the top-level volumes key.

**Comment by fwsmit** [comment]
Yes, the podman implementation seems like a bug. I'll open a new issue about it.
