### ISSUE TITLE
build: OSError: Dockerfile not found in .

### ISSUE THREAD

**Issue by Yajo** [containers/podman-compose#75]
See the error:

```bash
# Cloned commit: f75d36ac141ede5dded989fcc158f9c02d143362
[root@cc701f6ac6f1 ~]# git clone https://github.com/Tecnativa/doodba-scaffolding
Cloning into 'doodba-scaffolding'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 1000 (delta 11), reused 11 (delta 8), pack-reused 979
Receiving objects: 100% (1000/1000), 158.13 KiB | 5.65 MiB/s, done.
Resolving deltas: 100% (648/648), done.

[root@cc701f6ac6f1 ~]# cd doodba-scaffolding/

[root@cc701f6ac6f1 doodba-scaffolding]# pip3 install podman-compose
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting podman-compose
  Downloading https://files.pythonhosted.org/packages/d8/1a/4eed53406776275302a9325555a3c389c7ad8fa35ab287e6d93c041b7de7/podman_compose-0.1.5-py2.py3-none-any.whl
Collecting pyyaml (from podman-compose)
  Downloading https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz (265kB)
     |████████████████████████████████| 266kB 22.9MB/s 
Installing collected packages: pyyaml, podman-compose
  Running setup.py install for pyyaml ... done
Successfully installed podman-compose-0.1.5 pyyaml-5.1.2

[root@cc701f6ac6f1 doodba-scaffolding]# podman-compose -f devel.yaml build
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 1093, in main
    podman_compose.run()
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 625, in run
    cmd(self, args)
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 782, in wrapped
    return func(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 850, in compose_build
    build_one(compose, args, cnt)
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 834, in build_one
    raise OSError("Dockerfile not found in "+ctx)
OSError: Dockerfile not found in .
```

**Comment by muayyad-alsadi** [comment]
please try to use the devel branch as in the readme

because the `extends` feature is in that branch.

**Comment by Yajo** [comment]
> BTW: this feature is removed from docker-compose file v3

Lol yes, that's why I still use v2 :stuck_out_tongue: 

Regarding the other thing:

```bash
[root@7332c1881663 doodba-scaffolding]# pip3 install pyyaml
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Collecting pyyaml
  Downloading https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz (265kB)
     |████████████████████████████████| 266kB 14.5MB/s 
Installing collected packages: pyyaml
  Running setup.py install for pyyaml ... done
Successfully installed pyyaml-5.1.2

[root@7332c1881663 doodba-scaffolding]# pip3 install git+https://github.com/containers/podman-compose --user
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting git+https://github.com/containers/podman-compose
  Cloning https://github.com/containers/podman-compose to /tmp/pip-req-build-ufn_mnb8
  Running command git clone -q https://github.com/containers/podman-compose /tmp/pip-req-build-ufn_mnb8
Requirement already satisfied: pyyaml in /usr/local/lib64/python3.7/site-packages (from podman-compose==0.1.6.dev0) (5.1.2)
Installing collected packages: podman-compose
  Running setup.py install for podman-compose ... done
Successfully installed podman-compose-0.1.6.dev0

[root@7332c1881663 doodba-scaffolding]# ~/.local/bin/podman-compose -f devel.yaml run --rm odoo bash
Traceback (most recent call last):
  File "/root/.local/bin/podman-compose", line 11, in <module>
    load_entry_point('podman-compose==0.1.6.dev0', 'console_scripts', 'podman-compose')()
  File "/root/.local/lib/python3.7/site-packages/podman_compose.py", line 1264, in main
    podman_compose.run()
  File "/root/.local/lib/python3.7/site-packages/podman_compose.py", line 739, in run
    self._parse_compose_file()
  File "/root/.local/lib/python3.7/site-packages/podman_compose.py", line 819, in _parse_compose_file
    flat_deps(services, with_extends=True)
  File "/root/.local/lib/python3.7/site-packages/podman_compose.py", line 614, in flat_deps
    rec_deps(services, name)
  File "/root/.local/lib/python3.7/site-packages/podman_compose.py", line 593, in rec_deps
    new_deps = rec_deps(services, dep_name, start_point)
  File "/root/.local/lib/python3.7/site-packages/podman_compose.py", line 593, in rec_deps
    new_deps = rec_deps(services, dep_name, start_point)
  File "/root/.local/lib/python3.7/site-packages/podman_compose.py", line 593, in rec_deps
    new_deps = rec_deps(services, dep_name, start_point)
  [Previous line repeated 991 more times]
  File "/root/.local/lib/python3.7/site-packages/podman_compose.py", line 586, in rec_deps
    for dep_name in deps.copy():
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by Yajo** [comment]
After #76 was fixed, it works fine. Thanks!
