### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by limburgher** [containers/podman-compose#76]
git clone git@github.com:Tecnativa/doodba-scaffolding.git
cd doodba-scaffolding
podman-compose -f devel.yaml up -d
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 11, in <module>
    load_entry_point('podman-compose==0.1.6.dev0', 'console_scripts', 'podman-compose')()
  File "/usr/lib/python3.7/site-packages/podman_compose.py", line 1263, in main
    podman_compose.run()
  File "/usr/lib/python3.7/site-packages/podman_compose.py", line 738, in run
    self._parse_compose_file()
  File "/usr/lib/python3.7/site-packages/podman_compose.py", line 818, in _parse_compose_file
    flat_deps(services, with_extends=True)
  File "/usr/lib/python3.7/site-packages/podman_compose.py", line 613, in flat_deps
    rec_deps(services, name)
  File "/usr/lib/python3.7/site-packages/podman_compose.py", line 592, in rec_deps
    new_deps = rec_deps(services, dep_name, start_point)
  File "/usr/lib/python3.7/site-packages/podman_compose.py", line 592, in rec_deps
    new_deps = rec_deps(services, dep_name, start_point)
  File "/usr/lib/python3.7/site-packages/podman_compose.py", line 592, in rec_deps
    new_deps = rec_deps(services, dep_name, start_point)
  [Previous line repeated 991 more times]
  File "/usr/lib/python3.7/site-packages/podman_compose.py", line 585, in rec_deps
    for dep_name in deps.copy():
RecursionError: maximum recursion depth exceeded while calling a Python object

This is on Fedora, podman-compose-0.1.5-1.git20191030.fc31.noarch

Other docker-compose files seem to work, including from this project.

**Comment by muayyad-alsadi** [comment]
the reason for this bug is that the service odoo extends a service called odoo (but in different files)
when both merged, it's fixed now

**Comment by limburgher** [comment]
Thank you so much!
