### ISSUE TITLE
TypeError: sequence item 6: expected str instance, int found

### ISSUE THREAD

**Issue by renich** [containers/podman-compose#77]
Trying to run https://github.com/puppetlabs/pupperware with podman-compose and I can't even start.

```
[renich@introdesk pupperware]$ podman-compose up
Traceback (most recent call last):
  File "/home/renich/.local/bin/podman-compose", line 10, in <module>
    sys.exit(main())
  File "/home/renich/.local/lib/python3.7/site-packages/podman_compose.py", line 1093, in main
    podman_compose.run()
  File "/home/renich/.local/lib/python3.7/site-packages/podman_compose.py", line 625, in run
    cmd(self, args)
  File "/home/renich/.local/lib/python3.7/site-packages/podman_compose.py", line 782, in wrapped
    return func(*args, **kw)
  File "/home/renich/.local/lib/python3.7/site-packages/podman_compose.py", line 895, in compose_up
    create_pods(compose, args)
  File "/home/renich/.local/lib/python3.7/site-packages/podman_compose.py", line 862, in create_pods
    compose.podman.run(podman_args)
  File "/home/renich/.local/lib/python3.7/site-packages/podman_compose.py", line 585, in run
    print("podman " + " ".join(podman_args))
TypeError: sequence item 6: expected str instance, int found
```

**Comment by renich** [comment]
My sysinfo: https://paste.centos.org/view/8cc6f84f

**Comment by muayyad-alsadi** [comment]
please try dev branch

**Comment by renich** [comment]
Will do.

**Comment by renich** [comment]
Dev branch works. You can close this one if you like. Congratulations! ;D

**Comment by lexfrei** [comment]
Same issue on 0.1.5 (can't compare it with 2019's dev in my brain)

Probably similar to https://github.com/kubernetes/kompose/issues/986#issuecomment-715556739

**Comment by stweil** [comment]
Please reopen this issue. It still occurs with the development version (see [example](https://github.com/UB-Mannheim/escriptorium/wiki#running-with-podman-compose-no-root)).

**Comment by stweil** [comment]
The failing Python statement is `print(" ".join(cmd_ls))`. There are other code lines which also don't like integer list elements: 

```
  File "/home/stweil/venv/lib/python3.9/site-packages/podman_compose.py", line 719, in run
    p = subprocess.Popen(cmd_ls)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1756, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not int
```

**Comment by stweil** [comment]
Pull request #305 should fix this issue.
