### ISSUE TITLE
[v1.0.6] podman-compose up -d throws errors

### ISSUE THREAD

**Issue by kskarthik** [containers/podman-compose#775]
**Describe the bug**

Tried bringing up the containers defined in the compose file. 

File https://gitlab.com/gnukhata/gkcore/-/blob/devel/docker-compose.yaml?ref_type=heads

**Expected behavior**
I expected it to bring up all containers normally

**Actual behavior**
It throws errors defined below :arrow_down: and exits with code 125

**Output**
```
kar@earth:~/my/work/gkcore$ podman-compose up -d
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.5.1
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=gkcore', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files ("/home/kar/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools
podman volume inspect gkcore_gkdb || podman volume create gkcore_gkdb
['podman', 'volume', 'inspect', 'gkcore_gkdb']
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files ("/home/kar/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools
['podman', 'network', 'exists', 'gkcore_default']
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files ("/home/kar/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools
podman run --name=gkcore_db_1 -d --label io.podman.compose.config-hash=73edf7c8df9fd158f14d6eab8570d280d2e09a772ce80a1ae66e28312099c0c5 --label io.podman.compose.project=gkcore --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@gkcore.service --label com.docker.compose.project=gkcore --label com.docker.compose.project.working_dir=/home/kar/my/work/gkcore --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=db -e POSTGRES_USER=gkadmin -e POSTGRES_PASSWORD=gkadmin -e POSTGRES_DB=gkdata -v gkcore_gkdb:/var/lib/postgresql/data --net gkcore_default --network-alias db -p 5432:5432 postgres:12-alpine
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files ("/home/kar/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools
Error: short-name "postgres:12-alpine" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
exit code: 125
podman start gkcore_db_1
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files ("/home/kar/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools
Error: no container with name or ID "gkcore_db_1" found: no such container
exit code: 125
['podman', 'network', 'exists', 'gkcore_default']
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files ("/home/kar/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools
podman run --name=gkcore_ifsc-server_1 -d --label io.podman.compose.config-hash=73edf7c8df9fd158f14d6eab8570d280d2e09a772ce80a1ae66e28312099c0c5 --label io.podman.compose.project=gkcore --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@gkcore.service --label com.docker.compose.project=gkcore --label com.docker.compose.project.working_dir=/home/kar/my/work/gkcore --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=ifsc-server --net gkcore_default --network-alias ifsc-server razorpay/ifsc:latest
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files ("/home/kar/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools
Error: short-name "razorpay/ifsc:latest" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
exit code: 125
podman start gkcore_ifsc-server_1
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files ("/home/kar/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools
Error: no container with name or ID "gkcore_ifsc-server_1" found: no such container
exit code: 125
podman volume inspect gkcore_pgadmin || podman volume create gkcore_pgadmin
['podman', 'volume', 'inspect', 'gkcore_pgadmin']
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files ("/home/kar/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools
['podman', 'network', 'exists', 'gkcore_default']
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files ("/home/kar/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools
podman run --name=gkcore_pgadmin_1 -d --label io.podman.compose.config-hash=73edf7c8df9fd158f14d6eab8570d280d2e09a772ce80a1ae66e28312099c0c5 --label io.podman.compose.project=gkcore --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@gkcore.service --label com.docker.compose.project=gkcore --label com.docker.compose.project.working_dir=/home/kar/my/work/gkcore --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=pgadmin -e PGADMIN_DEFAULT_EMAIL=admin@gkcore.gk -e PGADMIN_DEFAULT_PASSWORD=admin -v gkcore_pgadmin:/var/lib/pgadmin --net gkcore_default --network-alias pgadmin -p 3000:80 dpage/pgadmin4:latest
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files ("/home/kar/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools
Error: short-name "dpage/pgadmin4:latest" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
exit code: 125
podman start gkcore_pgadmin_1
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files ("/home/kar/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools
Error: no container with name or ID "gkcore_pgadmin_1" found: no such container
exit code: 125
podman volume inspect gkcore_gkdb_old || podman volume create gkcore_gkdb_old
['podman', 'volume', 'inspect', 'gkcore_gkdb_old']
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files ("/home/kar/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools
['podman', 'network', 'exists', 'gkcore_default']
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files ("/home/kar/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools
podman run --name=gkcore_gkwebapp_1 -d --label io.podman.compose.config-hash=73edf7c8df9fd158f14d6eab8570d280d2e09a772ce80a1ae66e28312099c0c5 --label io.podman.compose.project=gkcore --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@gkcore.service --label com.docker.compose.project=gkcore --label com.docker.compose.project.working_dir=/home/kar/my/work/gkcore --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=gkwebapp -v gkcore_gkdb_old:/var/lib/postgresql --net gkcore_default --network-alias gkwebapp -p 6544:6544 digitalfreedom/gnukhata:v7.0update
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files ("/home/kar/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools
Error: short-name "digitalfreedom/gnukhata:v7.0update" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
exit code: 125
podman start gkcore_gkwebapp_1
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files ("/home/kar/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools
Error: no container with name or ID "gkcore_gkwebapp_1" found: no such container
exit code: 125
```
**Environment:**
 - OS: Linux (Debian Sid)

```
kar@earth:~$ podman-compose -v
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.5.1
podman-compose version 1.0.6
podman --version
podman version 4.5.1
exit code: 0
kar@earth:~$ podman -v
podman version 4.5.1
```

**Additional context**

**Comment by geekscrapy** [comment]
Same (flavor) issue here:
```
$ podman-compose  -v
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 3.0.1
podman-compose version 1.0.6
podman --version 
podman version 3.0.1
exit code: 0
```

```
$ podman-compose -f compose.yml up  
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 3.0.1
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=user1', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
['podman', 'network', 'exists', 'user1_default']
Error: unrecognized command `podman network exists`
Try 'podman network --help' for more information.
['podman', 'network', 'create', '--label', 'io.podman.compose.project=user1', '--label', 'com.docker.compose.project=user1', 'user1_default']
Error: the network name user1_default is already used
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 720, in assert_cnt_nets
    compose.podman.output([], "network", ["exists", net_name])
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1098, in output
    return subprocess.check_output(cmd_ls)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['podman', 'network', 'exists', 'user1_default']' returned non-zero exit status 125.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 2941, in main
    podman_compose.run()
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1423, in run
    cmd(self, args)
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1754, in wrapped
    return func(*args, **kw)
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 2067, in compose_up
    podman_args = container_to_args(compose, cnt, detached=args.detach)
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 903, in container_to_args
    assert_cnt_nets(compose, cnt)
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 761, in assert_cnt_nets
    compose.podman.output([], "network", args)
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1098, in output
    return subprocess.check_output(cmd_ls)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['podman', 'network', 'create', '--label', 'io.podman.compose.project=user1', '--label', 'com.docker.compose.project=user1', 'user1_default']' returned non-zero exit status 125.
```

Seems to be an issue with network creation:
`Error: unrecognized command `podman network exists`

**Comment by mokibit** [comment]
Closing this issue as this error is not a bug in `podman-compose`, but rather a Podman configuration / Docker-compatibility gap.

The error `short-name "postgres:12-alpine" did not resolve to an alias and no unqualified-search registries are defined` is caused by Podman's stricter image name resolution. Unlike Docker, Podman does not silently default to `docker.io` for unqualified image names.

You can fix this by using fully-qualified image names in your Compose file, or by adding `docker.io` to your `unqualified-search-registries` in `/etc/containers/registries.conf`.

Minimal reproduction showing that it works:
`docker-compose.yml`
```
services:
  db:
    image: docker.io/library/postgres:12-alpine
    environment:
      - POSTGRES_USER=gkadmin
      - POSTGRES_PASSWORD=gkadmin
      - POSTGRES_DB=gkdata
    ports:
      - "5432:5432"
    volumes:
      - gkdb:/var/lib/postgresql/data

volumes:
  gkdb:

```
Commands:
```
$ podman-compose up -d
[...]
test-podman-compose_db_1
$ podman ps -a --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"
NAMES                     IMAGE                                                              STATUS
test-podman-compose_db_1  docker.io/library/postgres:12-alpine                               Up 20 seconds
```
The container starts successfully when the fully-qualified image name is used.

**Comment by mokibit** [comment]
As for a another comment from user @geekscrapy — this is not the same issue as reported by the OP. Your problem is a Podman version compatibility issue, not a bug in `podman-compose` itself. 

The error is:
```
Error: unrecognized command `podman network exists`
```
The `podman network exists` command was introduced in a later Podman release (not present in 3.0.1). Because `podman-compose` 1.0.6 relies on `podman network exists` to check whether a network already exists, the check fails with exit code 125. The subsequent `podman network create` then also fails because the network was already created in a previous run.

What you can do
1. Upgrade Podman to a version that supports `podman network exists`
2. Workaround for Podman 3.0.1: manually remove the existing network before running `podman-compose up`:
   ```
   podman network rm user1_default
   podman-compose up
   ```
   (You may need to do this every time if the network creation logic keeps conflicting.)

The printed Python lists (e.g., `['podman', 'ps', '--filter', ...]`) were part of the default output in older `podman-compose` versions and are unrelated to the crash. Newer versions suppress this unless `--verbose` is used.

Please open a new issue with the details you posted above. That will help maintainers decide whether to add backward-compatibility shims or document the minimum required Podman version more clearly.
