### ISSUE TITLE
KeyError: 'target' in podman-compose up --build

### ISSUE THREAD

**Issue by brunomcuesta** [containers/podman-compose#791]
Hello!
I'm trying to create [DefectDojo](https://github.com/DefectDojo/django-DefectDojo) image with a docker-compose.yml, but I get an error in a podman-compose function.

**To Reproduce**
1. Run the following command to build the images.

`podman-compose up --build`

**Expected behavior**
Create images and containers without errors.

**Actual behavior**
I get the error on line 470 of the container_to_ulimit_args() function:

https://github.com/containers/podman-compose/blob/bce40c2db30fb0ffb9264b5f51535c26f48fe983/podman_compose.py#L470

**Output**

```
podman volume inspect django-defectdojo_defectdojo_media || podman volume create django-defectdojo_defectdojo_media
['podman', 'volume', 'inspect', 'django-defectdojo_defectdojo_media']
Error: no such volume django-defectdojo_defectdojo_media
['podman', 'volume', 'create', '--label', 'io.podman.compose.project=django-defectdojo', '--label', 'com.docker.compose.project=django-defectdojo', 'django-defectdojo_defectdojo_media']
['podman', 'volume', 'inspect', 'django-defectdojo_defectdojo_media']
['podman', 'network', 'exists', 'django-defectdojo_default']
podman create --name=django-defectdojo_uwsgi_1 --requires=django-defectdojo_postgres_1 --label io.podman.compose.config-hash=1b4ca7b998295293580690286b35519aa60ccb4ad5e21a78a88b018534eef04d --label io.podman.compose.project=django-defectdojo --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@django-defectdojo.service --label com.docker.compose.project=django-defectdojo --label com.docker.compose.project.working_dir=/home/bruno/Pentest/DefectDojo/django-DefectDojo --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=uwsgi -e DD_DEBUG=False -e DD_DJANGO_METRICS_ENABLED=False -e DD_ALLOWED_HOSTS=* -e DD_DATABASE_URL= -e DD_CELERY_BROKER_URL= -e DD_SECRET_KEY=hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq -e DD_CREDENTIAL_AES_256_KEY=&91a*agLqesc*0DJ+2*bAbsUZfR*4nLw -v ./docker/extra_settings:/app/docker/extra_settings -v django-defectdojo_defectdojo_media:/app/media --net django-defectdojo_default --network-alias uwsgi --entrypoint ["/entrypoint-uwsgi.sh"] defectdojo/defectdojo-django:latest
b913b2860514deea21aedc54c3b8f2c7d8906d3a7d7da6b2122de8b4801e4172
exit code: 0
Traceback (most recent call last):
  File "/home/bruno/.local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/home/bruno/.local/lib/python3.10/site-packages/podman_compose.py", line 2941, in main
    podman_compose.run()
  File "/home/bruno/.local/lib/python3.10/site-packages/podman_compose.py", line 1423, in run
    cmd(self, args)
  File "/home/bruno/.local/lib/python3.10/site-packages/podman_compose.py", line 1754, in wrapped
    return func(*args, **kw)
  File "/home/bruno/.local/lib/python3.10/site-packages/podman_compose.py", line 2067, in compose_up
    podman_args = container_to_args(compose, cnt, detached=args.detach)
  File "/home/bruno/.local/lib/python3.10/site-packages/podman_compose.py", line 901, in container_to_args
    podman_args.extend(get_mount_args(compose, cnt, volume))
  File "/home/bruno/.local/lib/python3.10/site-packages/podman_compose.py", line 530, in get_mount_args
    args = mount_desc_to_volume_args(compose, volume, srv_name, cnt["name"])
  File "/home/bruno/.local/lib/python3.10/site-packages/podman_compose.py", line 470, in mount_desc_to_volume_args
    target = mount_desc["target"]
KeyError: 'target'
...

The volumes are created despite the error.

**Command**:

`podman volume inspect django-defectdojo_defectdojo_media`

**Output**:

```
[
     {
          "Name": "django-defectdojo_defectdojo_media",
          "Driver": "local",
          "Mountpoint": "/home/bruno/.local/share/containers/storage/volumes/django-defectdojo_defectdojo_media/_data",
          "CreatedAt": "2023-10-16T16:01:05.093457972-03:00",
          "Labels": {
               "com.docker.compose.project": "django-defectdojo",
               "io.podman.compose.project": "django-defectdojo"
          },
          "Scope": "local",
          "Options": {},
          "MountCount": 0,
          "NeedsCopyUp": true,
          "NeedsChown": true,
          "LockNumber": 5
     }
]
```

The docker-compose.yml file:

```
---
version: '3.8'
services:
  nginx:
    build:
      context: ./
      dockerfile: "Dockerfile.nginx-${DEFECT_DOJO_OS:-debian}"
    image: "defectdojo/defectdojo-nginx:${NGINX_VERSION:-latest}"
    volumes:
      - defectdojo_media:/usr/share/nginx/html/media
    depends_on:
      - uwsgi
    environment:
      NGINX_METRICS_ENABLED: "${NGINX_METRICS_ENABLED:-false}"
    ports:
      - target: 8080
        published: ${DD_PORT:-8080}
        protocol: tcp
        mode: host
      - target: 8443
        published: ${DD_TLS_PORT:-8443}
        protocol: tcp
        mode: host
  uwsgi:
    build:
      context: ./
      dockerfile: "Dockerfile.django-${DEFECT_DOJO_OS:-debian}"
      target: django
    image: "defectdojo/defectdojo-django:${DJANGO_VERSION:-latest}"
    volumes:
        - type: bind
          source: ./docker/extra_settings
          target: /app/docker/extra_settings
        - "defectdojo_media:${DD_MEDIA_ROOT:-/app/media}"
    depends_on:
      - ${DD_DOCKERCOMPOSE_DATABASE:-postgres}
    entrypoint: ['/entrypoint-uwsgi.sh']
    environment:
      DD_DEBUG: 'False'
      DD_DJANGO_METRICS_ENABLED: "${DD_DJANGO_METRICS_ENABLED:-False}"
      DD_ALLOWED_HOSTS: "${DD_ALLOWED_HOSTS:-*}"
      DD_DATABASE_URL: ${DD_DATABASE_URL}
      DD_CELERY_BROKER_URL: ${DD_CELERY_BROKER_URL}
      DD_SECRET_KEY: "${DD_SECRET_KEY:-hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq}"
      DD_CREDENTIAL_AES_256_KEY: "${DD_CREDENTIAL_AES_256_KEY:-&91a*agLqesc*0DJ+2*bAbsUZfR*4nLw}"
  celerybeat:
    image: "defectdojo/defectdojo-django:${DJANGO_VERSION:-latest}"
    depends_on:
      - ${DD_DOCKERCOMPOSE_DATABASE:-postgres}
      - ${DD_DOCKERCOMPOSE_BROKER:-redis}
    entrypoint: ['/entrypoint-celery-beat.sh']
    environment:
      DD_DATABASE_URL: ${DD_DATABASE_URL}
      DD_CELERY_BROKER_URL: ${DD_CELERY_BROKER_URL}
      DD_SECRET_KEY: "${DD_SECRET_KEY:-hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq}"
      DD_CREDENTIAL_AES_256_KEY: "${DD_CREDENTIAL_AES_256_KEY:-&91a*agLqesc*0DJ+2*bAbsUZfR*4nLw}"
    volumes:
        - type: bind
          source: ./docker/extra_settings
          target: /app/docker/extra_settings
  celeryworker:
    image: "defectdojo/defectdojo-django:${DJANGO_VERSION:-latest}"
    volumes:
        - type: bind
          source: ./docker/extra_settings
          target: /app/docker/extra_settings
        - "defectdojo_media:${DD_MEDIA_ROOT:-/app/media}"
    depends_on:
      - ${DD_DOCKERCOMPOSE_DATABASE:-postgres}
      - ${DD_DOCKERCOMPOSE_BROKER:-redis}
    entrypoint: ['/entrypoint-celery-worker.sh']
    environment:
      DD_DATABASE_URL: ${DD_DATABASE_URL}
      DD_CELERY_BROKER_URL: ${DD_CELERY_BROKER_URL}
      DD_SECRET_KEY: "${DD_SECRET_KEY:-hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq}"
      DD_CREDENTIAL_AES_256_KEY: "${DD_CREDENTIAL_AES_256_KEY:-&91a*agLqesc*0DJ+2*bAbsUZfR*4nLw}"
  initializer:
    image: "defectdojo/defectdojo-django:${DJANGO_VERSION:-latest}"
    volumes:
        - type: bind
          source: ./docker/extra_settings
    depends_on:
      - ${DD_DOCKERCOMPOSE_DATABASE:-postgres}
    entrypoint: ['/entrypoint-initializer.sh']
    environment:
      DD_DATABASE_URL: ${DD_DATABASE_URL}
      DD_ADMIN_USER: "${DD_ADMIN_USER:-admin}"
      DD_ADMIN_MAIL: "${DD_ADMIN_USER:-admin@defectdojo.local}"
      DD_ADMIN_FIRST_NAME: "${DD_ADMIN_FIRST_NAME:-Admin}"
      DD_ADMIN_LAST_NAME: "${DD_ADMIN_LAST_NAME:-User}"
      DD_INITIALIZE: "${DD_INITIALIZE:-true}"
      DD_SECRET_KEY: "${DD_SECRET_KEY:-hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq}"
      DD_CREDENTIAL_AES_256_KEY: "${DD_CREDENTIAL_AES_256_KEY:-&91a*agLqesc*0DJ+2*bAbsUZfR*4nLw}"
  postgres:
    image: postgres:16.0-alpine@sha256:2ccd6655060d7b06c71f86094e8c7a28bdcc8a80b43baca4b1dabb29cff138a2
    volumes:
      - defectdojo_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DD_DATABASE_NAME}
      POSTGRES_USER: ${DD_DATABASE_USER}
      POSTGRES_PASSWORD: ${DD_DATABASE_PASSWORD}
  redis:
    image: redis:7.2.1-alpine@sha256:9150d86fe2a9d03bbdb15bb9758fa5e3d24632386af8f6eb4d675ee4c976f499
    volumes:
      - defectdojo_redis:/data
volumes:
  defectdojo_media: {}
  defectdojo_postgres: {}
  defectdojo_redis: {}

```

**Environment:**
 - OS: Ubuntu 22.04.3 LTS (Jammy Jellyfish)
 - podman version: 4.6.2
 - podman compose version: 1.0.6

Could it be a podman-compose bug or is there something wrong with docker-compose.yml?
Thanks!

**Comment by brunomcuesta** [comment]
The problem was in the section celeryworker. It must be:

```
volumes:
        - type: bind
          source: ./docker/extra_settings
          target: /app/docker/extra_settings
```

**Comment by yogo1212** [comment]
@brunomcuesta can you close this?
