### ISSUE TITLE
podman-compose run -e doesn't like values with equals signs

### ISSUE THREAD

**Issue by aripollak** [containers/podman-compose#798]
**Describe the bug**
Passing an environment variable value that contains equals signs to `podman-compose run -e`, like base64 results used in e.g. AWS_SESSION_TOKEN, crashes podman-compose.

**To Reproduce**
With a simple docker-compose.yml:
```
services:
  bash:
    image: bash
```

Run:
`podman-compose run --rm -e FOO=bar= bash -c 'echo $FOO'`

**Expected behavior**
I expected this to print out `bar=`, like what happens if you run `podman run --rm -e FOO=bar= bash -c 'echo $FOO'`.

**Actual behavior**
```
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.3.1
Traceback (most recent call last):
  File "/home/ari/bin/podman-compose", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ari/.local/pipx/venvs/podman-compose/lib/python3.11/site-packages/podman_compose.py", line 2941, in main
    podman_compose.run()
  File "/home/ari/.local/pipx/venvs/podman-compose/lib/python3.11/site-packages/podman_compose.py", line 1423, in run
    cmd(self, args)
  File "/home/ari/.local/pipx/venvs/podman-compose/lib/python3.11/site-packages/podman_compose.py", line 1754, in wrapped
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/home/ari/.local/pipx/venvs/podman-compose/lib/python3.11/site-packages/podman_compose.py", line 2269, in compose_run
    additional_env_vars = dict(map(lambda each: each.split("="), args.env))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: dictionary update sequence element #0 has length 4; 2 is required
```

**Output**

```
$ podman-compose version
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.3.1
podman-compose version 1.0.6
podman --version 
podman version 4.3.1
exit code: 0


$ podman-compose up
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.3.1
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=ari', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
['podman', 'network', 'exists', 'ari_default']
podman create --name=ari_bash_1 --label io.podman.compose.config-hash=4aec29ce37cf4ba4b08f025e550fa79112f20ffdda092250d752f913d61465b6 --label io.podman.compose.project=ari --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@ari.service --label com.docker.compose.project=ari --label com.docker.compose.project.working_dir=/home/ari --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=bash --net ari_default --network-alias bash bash
8936897a95b697c424a6a124013ee5bffb3b49f9099df8304511adfccde175a3
exit code: 0
podman start -a ari_bash_1

exit code: 0

```

**Environment:**
 - OS: Ubuntu 23.04
 - podman version: 4.3.1
 - podman compose version: 1.0.6

**Additional context**

**Comment by aripollak** [comment]
Note that this also fails in `podman-compose exec -e FOO=bar=` for a similar reason.
