### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv' - right after pip3 install podman-compose inside a conda environment?

### ISSUE THREAD

**Issue by epicwhale** [containers/podman-compose#826]
**Describe the bug**
I am installing podman-compose for the first time inside my conda environment.

I did a `pip3 install podman-compose`

But when I run any podman-compose command, for example `podman-compose --version`, I get a:

```
$ podman-compose --version  
Traceback (most recent call last):
  File "/Users/dayson/code/localschengenappointments/.conda/bin/podman-compose", line 5, in <module>
    from podman_compose import main
  File "/Users/dayson/code/localschengenappointments/.conda/lib/python3.11/site-packages/podman_compose.py", line 39, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
```

I then installed `pip3 install python-dotenv` and confirmed I have `python-dotenv                 1.0.0` in my pip3 list, and its the same pip that's associated with the python in the conda environment. Still running into the same error.

**Output**

**Environment:**
 - OS: Mac
 - podman version:  l 4.9.0
 - podman compose version: 1.0.6

What am I doing incorrectly? Shouldn't all dependencies be autoinstalled if I use the pip approach for installing podman-compose

Thanks!

**Comment by davidkhala** [comment]
I see the some error if we follow the README.md on how to manual install it. 
```
curl -o ~/.local/bin/podman-compose https://raw.githubusercontent.com/containers/podman-compose/main/podman_compose.py
chmod +x ~/.local/bin/podman-compose
```


then when run `podman compose`, you will get
```
>>>> Executing external compose provider "/home/vpcuser/.local/bin/podman-compose". Please see podman-compose(1) for how to disable this message. <<<<

Traceback (most recent call last):
  File "/home/vpcuser/.local/bin/podman-compose", line 45, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
```
