### ISSUE TITLE
Podman cannot create (inspect) volume

### ISSUE THREAD

**Issue by Michael-Jurek** [containers/podman-compose#84]
I am trying to replace docker-compose with podman-compose. When run **podman-compose up --build**. Images have been built successfully and pod has started. Afterwards, when I want to create volume, following error appears.
```
.........
podman pod create --name=vmaas --share net -p 5432:5432 -p 8082:8082 -p 8730:8730 -p 9090:9090 -p 3000:3000 -p 8080:8080 -p 8081:8081 -p 8083:8083
7929ba1407c8341d05650487a71743c3db0ad92ffe8834d1d78eb7dedfe731d8
0
podman volume inspect vmaas_vmaas-db-data || podman volume create vmaas_vmaas-db-data
Error: no volume with name "vmaas_vmaas-db-data" found: no such volume
Error: error creating volume directory "/home/mjurek/.local/share/containers/storage/volumes/vmaas_vmaas-db-data/_data": mkdir /home/mjurek/.local/share/containers/storage/volumes/vmaas_vmaas-db-data/_data: file exists
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 362, in mount_dict_vol_to_bind
    try: out = compose.podman.output(["volume", "inspect", vol_name])
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 582, in output
    return subprocess.check_output(cmd)
  File "/usr/lib64/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['podman', 'volume', 'inspect', 'vmaas_vmaas-db-data']' returned non-zero exit status 125.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 1093, in main
    podman_compose.run()
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 625, in run
    cmd(self, args)
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 782, in wrapped
    return func(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 898, in compose_up
    detached=args.detach, podman_command=podman_command)
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 457, in container_to_args
    mount_args = mount_desc_to_args(compose, volume, cnt['_service'], cnt['name'])
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 386, in mount_desc_to_args
    mount_desc = mount_dict_vol_to_bind(compose, fix_mount_dict(mount_desc, proj_name, srv_name))
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 364, in mount_dict_vol_to_bind
    compose.podman.output(["volume", "create", "-l", "io.podman.compose.project={}".format(proj_name), vol_name])
  File "/usr/local/lib/python3.7/site-packages/podman_compose.py", line 582, in output
    return subprocess.check_output(cmd)
  File "/usr/lib64/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['podman', 'volume', 'create', '-l', 'io.podman.compose.project=vmaas', 'vmaas_vmaas-db-data']' returned non-zero exit status 125.

```
**podman version:**
```
podman==1.6.0
```
**podman-compose version:**
```
podman-compose==0.1.6.dev0
```

**docker-compose.yml**:
```
version: '3'

services:
  vmaas_database:
    container_name: vmaas-database
    build:
        context: .
        dockerfile: ./database/Dockerfile
    image: vmaas/database:latest
    restart: unless-stopped
    env_file:
      - ./conf/database-connection-admin.env
    ports:
      - 5432:5432
    volumes:
      - vmaas-db-data:/var/lib/pgsql/data

  vmaas_websocket:
    container_name: vmaas-websocket
    build:
        context: .
        dockerfile: ./websocket/Dockerfile
    image: vmaas/websocket:latest
    restart: unless-stopped
    ports:
      - 8082:8082

  vmaas_reposcan:
    container_name: vmaas-reposcan
    build:
        context: .
        dockerfile: ./reposcan/Dockerfile
    image: vmaas/reposcan:latest
    restart: unless-stopped
    env_file:
      - ./conf/database-connection-writer.env
      - ./conf/reposcan.env
    ports:
      - 8081:8081
      - 8730:8730
    volumes:
      - vmaas-reposcan-tmp:/tmp
      - vmaas-dump-data:/data:z
    depends_on:
      - vmaas_websocket
      - vmaas_database

  vmaas_webapp:
    container_name: vmaas-webapp
    build:
        context: .
        dockerfile: ./webapp/Dockerfile
    image: vmaas/webapp:latest
    restart: unless-stopped
    env_file:
      - ./conf/webapp.env
    ports:
      - 8080:8080
    depends_on:
      - vmaas_websocket
      - vmaas_reposcan

    
  vmaas_webapp_utils:
    container_name: vmaas-webapp-utils
    build:
        context: .
        dockerfile: ./webapp_utils/Dockerfile
    image: vmaas/webapp_utils:latest
    restart: unless-stopped
    env_file:
      - ./conf/webapp_utils.env
      - ./conf/database-connection-reader.env
    ports:
      - 8083:8083
    depends_on:
      - vmaas_webapp


  vmaas_prometheus:
    container_name: vmaas-prometheus
    image: prom/prometheus:v2.1.0
    volumes:
      - prometheus-data:/prometheus
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    security_opt:
      - label=disable
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - vmaas_reposcan
      - vmaas_webapp
    restart: always

  vmaas_grafana:
    container_name: vmaas-grafana
    image: grafana/grafana:6.2.5
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - vmaas_prometheus
    ports:
      - 3000:3000
    env_file:
      - ./monitoring/grafana/grafana.conf
    user: "104"
    restart: always

volumes:
  vmaas-db-data:
  vmaas-dump-data:
  vmaas-reposcan-tmp:
  prometheus-data:
  grafana-data:

```

**Comment by muayyad-alsadi** [comment]
the following shell command 

```
podman volume inspect vmaas_vmaas-db-data || podman volume create vmaas_vmaas-db-data
```

means if the volume does not exists, create it. it's a normal `podman` command, it's not `podman-compose`.

most likely your problem is a result of normal unix permissions
you don't have permission or HOME env points to different place

it's not a podman-compose bug

**Comment by Michael-Jurek** [comment]
Ok, I got it. Creating volume with rootless podman. That's probably issue with SELinux. When I run
 ```sudo podman-compose up --build```,
it seems to work well.
Thanks for advice.

**Comment by muayyad-alsadi** [comment]
It should work fine with selinux
