### ISSUE TITLE
RuntimeError: volume not defined in top level

### ISSUE THREAD

**Issue by virzak** [containers/podman-compose#903]
**Describe the bug**

Please make sure it's not a bug in podman (in that case report it to podman)
or your understanding of docker-compose or how rootless containers work (for example, it's normal for rootless container not to be able to listen for port less than 1024 like 80)

please try to reproduce the bug in latest devel branch

**To Reproduce**

Create yaml file:

```yaml
version: "3"

services:
  simple:
    image: alpine
    volumes:
      - \\wsl.localhost\Ubuntu:/ub
```

run
`podman compose -f docker-compose.yml up`

**Expected behavior**
Should return success

**Actual behavior**
returns error.

**Output**

```
🚀  podman-compose version           
podman-compose version 1.0.7
podman.exe version 5.0.0


🚀  podman-compose -f docker-compose.yml up
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\podman-compose.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\podman_compose.py", line 3245, in main
    asyncio.run(async_main())
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\podman_compose.py", line 3241, in async_main
    await podman_compose.run()
  File "C:\Python312\Lib\site-packages\podman_compose.py", line 1569, in run
    self._parse_compose_file()
  File "C:\Python312\Lib\site-packages\podman_compose.py", line 1792, in _parse_compose_file
    raise RuntimeError(f"volume [{vol_name}] not defined in top level")
RuntimeError: volume [\\wsl.localhost\Ubuntu] not defined in top level
```

**Environment:**
 - OS: Windows
 - podman version: 5.0.0
 - podman compose version: latest development

**Additional context**

This is an absolute must to be able to use docker-compose with vscode.

**Comment by gbschenkel** [comment]
If you are running podman inside the ubuntu(WSL), just do:
```
version: "3"

services:
  simple:
    image: alpine
    volumes:
      - ./ub:/ub
```
It will use the currently directory where the composer.yaml is.

Now is you don't are using podman inside the container, as a directory, you need set a `volumes`, but you need check how to do that, the common is use `driver: local`, need do a research on the other types of driver.

Example:
```
version: "3"

volumes:
  simple_data:
    driver: wsl # speculating
    path: \\wsl.localhost\Ubuntu # specutaling

services:
  simple:
    image: alpine
    volumes:
      - simple_data:/ub
```
