### ISSUE TITLE
Typo in error message for x-podman.gidmap

### ISSUE THREAD

**Issue by freezurbern** [containers/podman-compose#963]
**Describe the bug**
`x-podman.gidman` should be `x-podman.gidmap`
https://github.com/containers/podman-compose/blob/9599cc039eec35fcb5c2c606da50492c51636c63/podman_compose.py#L1146-L1151

**To Reproduce**

_docker-compose.yml_
```
services:
  ubuntu:
    image: docker.io/library/ubuntu
    user: "1000:100"
    x-podman:
      uidmap:
        - 0:1:1000
        - 1000:0:1
        - 1001:1001:64536
```

_commands_
```
$ podman-compose version
podman-compose version 1.1.0
podman version 3.4.4

$ podman-compose up
Traceback (most recent call last):
  File "/home/user/.local/bin/podman-compose", line 3472, in <module>
    main()
  File "/home/user/.local/bin/podman-compose", line 3468, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/.local/bin/podman-compose", line 3464, in async_main
    await podman_compose.run()
  File "/home/user/.local/bin/podman-compose", line 1740, in run
    retcode = await cmd(self, args)
  File "/home/user/.local/bin/podman-compose", line 2464, in compose_up
    podman_args = await container_to_args(compose, cnt, detached=args.detach)
  File "/home/user/.local/bin/podman-compose", line 1227, in container_to_args
    raise ValueError(
ValueError: Configuration under x-podman has been migrated to x-podman.uidmap and x-podman.gidman fields
```

**Comment by mokibit** [comment]
@freezurbern, thanks for opening an issue!
Fixed in https://github.com/containers/podman-compose/pull/965.
